import { useEffect, useMemo, useState } from "react";
import assetApi from "../../Services/assetApi.js";
import supplierApi from "../../Services/supplierApi.js";
import { downloadDataUrl, fileToDataUrl } from "../../utils/fileData.js";
import "../../styles/infinityModules.css";

const statuses=["OPERATIONAL","MAINTENANCE","DEFECTIVE","INACTIVE","REPLACED"];
const labels={OPERATIONAL:"Operacional",MAINTENANCE:"Manutenção",DEFECTIVE:"Com defeito",INACTIVE:"Inativo",REPLACED:"Substituído"};
const initial={name:"",category:"",assetTag:"",manufacturer:"",model:"",serialNumber:"",location:"",acquiredAt:"",warrantyUntil:"",supplierId:"",status:"OPERATIONAL",notes:"",file:null};
export default function Ativos(){
 const [items,setItems]=useState([]),[suppliers,setSuppliers]=useState([]),[form,setForm]=useState(initial),[editingId,setEditingId]=useState(null),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[feedback,setFeedback]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{const [a,s]=await Promise.all([assetApi.list(),supplierApi.list("?status=ACTIVE")]);setItems(a??[]);setSuppliers(s??[]);}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível carregar os ativos."});}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>items.filter(x=>{const q=search.trim().toLowerCase();return(!q||[x.name,x.category,x.assetTag,x.manufacturer,x.model,x.serialNumber,x.location].some(v=>String(v??"").toLowerCase().includes(q)))&&(!status||x.status===status);}),[items,search,status]);
 function edit(x){setEditingId(x.id);setForm({name:x.name??"",category:x.category??"",assetTag:x.assetTag??"",manufacturer:x.manufacturer??"",model:x.model??"",serialNumber:x.serialNumber??"",location:x.location??"",acquiredAt:x.acquiredAt?String(x.acquiredAt).slice(0,10):"",warrantyUntil:x.warrantyUntil?String(x.warrantyUntil).slice(0,10):"",supplierId:x.supplierId??"",status:x.status??"OPERATIONAL",notes:x.notes??"",file:null});setFeedback(null);}
 function reset(){setEditingId(null);setForm(initial);}
 async function save(e){e.preventDefault();setFeedback(null);setSaving(true);try{const payload={name:form.name,category:form.category,assetTag:form.assetTag||null,manufacturer:form.manufacturer||null,model:form.model||null,serialNumber:form.serialNumber||null,location:form.location||null,acquiredAt:form.acquiredAt||null,warrantyUntil:form.warrantyUntil||null,supplierId:form.supplierId||null,status:form.status,notes:form.notes||null};if(form.file){payload.attachmentFileName=form.file.name;payload.attachmentDataUrl=await fileToDataUrl(form.file);}if(editingId)await assetApi.update(editingId,payload);else await assetApi.create(payload);setFeedback({type:"ok",text:editingId?"Ativo atualizado.":"Ativo cadastrado."});reset();await load();}catch(err){setFeedback({type:"error",text:err?.details?.[0]?.message??err?.message??"Não foi possível salvar o ativo."});}finally{setSaving(false);}}
 async function download(x){try{const f=await assetApi.download(x.id);downloadDataUrl(f.dataUrl,f.fileName||x.attachmentFileName);}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível baixar o anexo."});}}
 async function remove(id){try{await assetApi.remove(id);setFeedback({type:"ok",text:"Ativo removido."});if(editingId===id)reset();await load();}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível remover o ativo."});}}
 return <div className="icm-page"><section className="icm-hero"><div><span className="icm-kicker">🧰 Patrimônio operacional</span><h1>Ativos e equipamentos</h1><p>Controle o inventário cadastral, localização, estado, garantia e fornecedor dos equipamentos do condomínio.</p></div><div className="icm-hero-count"><strong>{items.length}</strong><span>ativos</span></div></section>{feedback&&<div className={`icm-message icm-message-${feedback.type}`}>{feedback.text}</div>}
 <form className="icm-card icm-form" onSubmit={save}><h2>{editingId?"Editar ativo":"Novo ativo"}</h2><div className="icm-form-grid">
 <F label="Nome *"><input className="icm-input" required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></F><F label="Categoria *"><input className="icm-input" required minLength={2} value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Ex.: Câmera, computador, elevador"/></F>
 <F label="Patrimônio"><input className="icm-input" value={form.assetTag} onChange={e=>setForm({...form,assetTag:e.target.value})}/></F><F label="Número de série"><input className="icm-input" value={form.serialNumber} onChange={e=>setForm({...form,serialNumber:e.target.value})}/></F>
 <F label="Fabricante"><input className="icm-input" value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></F><F label="Modelo"><input className="icm-input" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></F>
 <F label="Localização"><input className="icm-input" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></F><F label="Fornecedor"><select className="icm-select" value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Sem fornecedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.tradeName||s.legalName}</option>)}</select></F>
 <F label="Data de aquisição"><input className="icm-input" type="date" value={form.acquiredAt} onChange={e=>setForm({...form,acquiredAt:e.target.value})}/></F><F label="Garantia até"><input className="icm-input" type="date" value={form.warrantyUntil} onChange={e=>setForm({...form,warrantyUntil:e.target.value})}/></F>
 <F label="Status"><select className="icm-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></F><F label={editingId?"Substituir anexo":"Anexo"}><input className="icm-input" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.txt,.jpg,.jpeg,.png,.webp" onChange={e=>setForm({...form,file:e.target.files?.[0]??null})}/></F>
 <F label="Observações" full><textarea className="icm-textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></F></div><div className="icm-actions"><button className="icm-btn icm-btn-primary" disabled={saving}>{saving?"Salvando...":editingId?"Salvar alterações":"Cadastrar ativo"}</button>{editingId&&<button type="button" className="icm-btn icm-btn-neutral" onClick={reset}>Cancelar edição</button>}</div></form>
 <div className="icm-toolbar"><input className="icm-input" placeholder="Buscar ativo..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="icm-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div>
 {loading?<div className="icm-card icm-empty">Carregando ativos...</div>:filtered.length===0?<div className="icm-card icm-empty">Nenhum ativo encontrado.</div>:<div className="icm-grid">{filtered.map(x=><article className="icm-card" key={x.id}><h3>{x.name}</h3><div className="icm-meta"><span className="icm-pill">{x.category}</span><span className={`icm-pill ${x.status==="OPERATIONAL"?"icm-status-ok":x.status==="DEFECTIVE"?"icm-status-urgent":x.status==="MAINTENANCE"?"icm-status-warning":"icm-status-neutral"}`}>{labels[x.status]||x.status}</span></div><div className="icm-detail-grid"><div><span>Patrimônio</span><strong>{x.assetTag||"—"}</strong></div><div><span>Local</span><strong>{x.location||"—"}</strong></div><div><span>Fornecedor</span><strong>{x.supplier?.tradeName||x.supplier?.legalName||"—"}</strong></div><div><span>Garantia</span><strong>{x.warrantyUntil?new Date(x.warrantyUntil).toLocaleDateString("pt-BR",{timeZone:"UTC"}):"—"}</strong></div></div><div className="icm-actions">{x.attachmentFilePath&&<button className="icm-btn icm-btn-soft" onClick={()=>download(x)}>Baixar anexo</button>}<button className="icm-btn icm-btn-neutral" onClick={()=>edit(x)}>Editar</button><button className="icm-btn icm-btn-danger" onClick={()=>remove(x.id)}>Remover</button></div></article>)}</div>}</div>;
}
function F({label,full=false,children}){return <div className={`icm-field${full?" icm-field-full":""}`}><label>{label}</label>{children}</div>}
