import { useEffect, useMemo, useState } from "react";
import contractApi from "../../Services/contractApi.js";
import supplierApi from "../../Services/supplierApi.js";
import { downloadDataUrl, fileToDataUrl } from "../../utils/fileData.js";
import "../../styles/infinityModules.css";

const statuses=["ACTIVE","EXPIRES_SOON","EXPIRED","CLOSED","CANCELED"];
const labels={ACTIVE:"Ativo",EXPIRES_SOON:"Próximo do vencimento",EXPIRED:"Vencido",CLOSED:"Encerrado",CANCELED:"Cancelado"};
const kindLabels={CONTRACT:"Contrato recorrente",ONE_OFF_SERVICE:"Serviço avulso"};
const initial={supplierId:"",contractKind:"CONTRACT",serviceType:"",reference:"",description:"",value:"",startDate:"",endDate:"",autoRenew:false,status:"ACTIVE",notes:"",file:null};
const cents=v=>{if(v===""||v==null)return null;const n=Number(String(v).replace(",","."));return Number.isFinite(n)&&n>=0?Math.round(n*100):null;};
const money=v=>v==null?"—":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
const dateBR=v=>v?new Date(v).toLocaleDateString("pt-BR",{timeZone:"UTC"}):"Não se aplica";

export default function Contratos(){
 const [items,setItems]=useState([]),[suppliers,setSuppliers]=useState([]),[form,setForm]=useState(initial),[editingId,setEditingId]=useState(null),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[kind,setKind]=useState(""),[feedback,setFeedback]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{const [c,s]=await Promise.all([contractApi.list(),supplierApi.list("?status=ACTIVE")]);setItems(c??[]);setSuppliers(s??[]);}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível carregar contratos e serviços."});}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>items.filter(x=>{const q=search.trim().toLowerCase();return(!q||[x.serviceType,x.reference,x.description,x.supplier?.legalName,x.supplier?.tradeName].some(v=>String(v??"").toLowerCase().includes(q)))&&(!status||x.status===status)&&(!kind||(x.contractKind??"CONTRACT")===kind);}),[items,search,status,kind]);
 const metrics=useMemo(()=>({contracts:items.filter(x=>(x.contractKind??"CONTRACT")==="CONTRACT").length,oneOff:items.filter(x=>x.contractKind==="ONE_OFF_SERVICE").length,warning:items.filter(x=>x.status==="EXPIRES_SOON").length,expired:items.filter(x=>x.status==="EXPIRED").length}),[items]);
 function edit(x){setEditingId(x.id);setForm({supplierId:x.supplierId??"",contractKind:x.contractKind??"CONTRACT",serviceType:x.serviceType??"",reference:x.reference??"",description:x.description??"",value:x.valueInCents==null?"":String((x.valueInCents/100).toFixed(2)).replace(".",","),startDate:x.startDate?String(x.startDate).slice(0,10):"",endDate:x.endDate?String(x.endDate).slice(0,10):"",autoRenew:Boolean(x.autoRenew),status:["CLOSED","CANCELED"].includes(x.status)?x.status:"ACTIVE",notes:x.notes??"",file:null});setFeedback(null);window.scrollTo?.({top:0,behavior:"smooth"});}
 function reset(){setEditingId(null);setForm(initial);}
 function changeKind(value){setForm(prev=>({...prev,contractKind:value,endDate:value==="ONE_OFF_SERVICE"?"":prev.endDate,autoRenew:value==="ONE_OFF_SERVICE"?false:prev.autoRenew}));}
 async function save(e){e.preventDefault();setFeedback(null);const valueInCents=cents(form.value);if(form.value&&valueInCents===null){setFeedback({type:"error",text:"Informe um valor válido."});return;}if(form.contractKind==="CONTRACT"&&!form.endDate){setFeedback({type:"error",text:"Informe o vencimento do contrato."});return;}setSaving(true);try{const payload={supplierId:form.supplierId,contractKind:form.contractKind,serviceType:form.serviceType,reference:form.reference||null,description:form.description,valueInCents,startDate:form.startDate,endDate:form.contractKind==="CONTRACT"?(form.endDate||null):null,autoRenew:form.contractKind==="CONTRACT"?form.autoRenew:false,status:form.status,notes:form.notes||null};if(form.file){payload.documentFileName=form.file.name;payload.documentDataUrl=await fileToDataUrl(form.file);}if(editingId)await contractApi.update(editingId,payload);else await contractApi.create(payload);setFeedback({type:"ok",text:editingId?"Registro atualizado.":form.contractKind==="CONTRACT"?"Contrato cadastrado.":"Serviço avulso cadastrado."});reset();await load();}catch(err){setFeedback({type:"error",text:err?.details?.[0]?.message??err?.message??"Não foi possível salvar o registro."});}finally{setSaving(false);}}
 async function download(x){try{const f=await contractApi.download(x.id);downloadDataUrl(f.dataUrl,f.fileName||x.documentFileName);}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível baixar o documento."});}}
 async function remove(id){try{await contractApi.remove(id);setFeedback({type:"ok",text:"Registro encerrado e removido da listagem ativa."});if(editingId===id)reset();await load();}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível remover o registro."});}}
 return <div className="icm-page">
  <section className="icm-hero"><div><span className="icm-kicker">📑 Gestão de serviços</span><h1>Contratos e serviços avulsos</h1><p>Controle contratos recorrentes e também trabalhos únicos executados por empresas, profissionais autônomos ou freelancers.</p></div><div className="icm-hero-count"><strong>{items.length}</strong><span>registros</span></div></section>
  <section className="icm-metrics"><div className="icm-metric"><span>Contratos</span><strong>{metrics.contracts}</strong></div><div className="icm-metric"><span>Serviços avulsos</span><strong>{metrics.oneOff}</strong></div><div className="icm-metric"><span>Vencendo em até 30 dias</span><strong>{metrics.warning}</strong></div><div className="icm-metric"><span>Vencidos</span><strong>{metrics.expired}</strong></div></section>
  {feedback&&<div className={`icm-message icm-message-${feedback.type}`}>{feedback.text}</div>}
  <form className="icm-card icm-form" onSubmit={save}><h2>{editingId?"Editar registro":"Novo contrato ou serviço"}</h2><div className="icm-form-grid"><F label="Modalidade *"><select className="icm-select" value={form.contractKind} onChange={e=>changeKind(e.target.value)}><option value="CONTRACT">Contrato recorrente</option><option value="ONE_OFF_SERVICE">Serviço avulso / trabalho único</option></select></F><F label="Fornecedor / profissional *"><select className="icm-select" required value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Selecione</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.tradeName||s.legalName}</option>)}</select></F><F label="Tipo de serviço *"><input className="icm-input" required minLength={2} value={form.serviceType} onChange={e=>setForm({...form,serviceType:e.target.value})}/></F><F label="Número / referência"><input className="icm-input" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></F><F label="Valor (R$)"><input className="icm-input" inputMode="decimal" placeholder="0,00" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></F><F label={form.contractKind==="CONTRACT"?"Início do contrato *":"Data do serviço *"}><input className="icm-input" type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></F>{form.contractKind==="CONTRACT"&&<F label="Vencimento *"><input className="icm-input" type="date" required value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></F>}<F label="Status"><select className="icm-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ACTIVE">Ativo</option><option value="CLOSED">Encerrado</option><option value="CANCELED">Cancelado</option></select></F><F label={editingId?"Substituir documento":"Documento / comprovante"}><input className="icm-input" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.txt,.jpg,.jpeg,.png,.webp" onChange={e=>setForm({...form,file:e.target.files?.[0]??null})}/></F><F label="Descrição do serviço *" full><textarea className="icm-textarea" required minLength={2} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></F><F label="Observações" full><textarea className="icm-textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></F>{form.contractKind==="CONTRACT"&&<label className="icm-check icm-field-full"><input type="checkbox" checked={form.autoRenew} onChange={e=>setForm({...form,autoRenew:e.target.checked})}/> Renovação automática prevista no contrato</label>}</div><div className="icm-actions"><button className="icm-btn icm-btn-primary" disabled={saving}>{saving?"Salvando...":editingId?"Salvar alterações":"Cadastrar"}</button>{editingId&&<button type="button" className="icm-btn icm-btn-neutral" onClick={reset}>Cancelar edição</button>}</div></form>
  <div className="icm-toolbar"><input className="icm-input" placeholder="Buscar contrato, serviço ou profissional..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="icm-select" value={kind} onChange={e=>setKind(e.target.value)}><option value="">Todas as modalidades</option><option value="CONTRACT">Contratos</option><option value="ONE_OFF_SERVICE">Serviços avulsos</option></select><select className="icm-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div>
  {loading?<div className="icm-card icm-empty">Carregando registros...</div>:filtered.length===0?<div className="icm-card icm-empty">Nenhum contrato ou serviço encontrado.</div>:<div className="icm-grid">{filtered.map(x=><article className="icm-card" key={x.id}><div className="icm-title-row"><span className="icm-file-icon">{x.contractKind==="ONE_OFF_SERVICE"?"🧰":"📑"}</span><div><h3>{x.serviceType}</h3><div className="icm-muted">{x.supplier?.tradeName||x.supplier?.legalName||"Fornecedor não informado"}</div></div></div><div className="icm-meta"><span className="icm-pill">{kindLabels[x.contractKind??"CONTRACT"]}</span><span className={`icm-pill ${x.status==="EXPIRED"?"icm-status-urgent":x.status==="EXPIRES_SOON"?"icm-status-warning":x.status==="ACTIVE"?"icm-status-ok":"icm-status-neutral"}`}>{labels[x.status]||x.status}</span>{x.reference&&<span className="icm-pill">{x.reference}</span>}</div><p className="icm-muted">{x.description}</p><div className="icm-detail-grid"><div><span>Valor</span><strong>{money(x.valueInCents)}</strong></div><div><span>{x.contractKind==="ONE_OFF_SERVICE"?"Data":"Início"}</span><strong>{dateBR(x.startDate)}</strong></div><div><span>Vencimento</span><strong>{x.contractKind==="ONE_OFF_SERVICE"?"Serviço avulso":dateBR(x.endDate)}</strong></div><div><span>Prazo</span><strong>{x.contractKind==="ONE_OFF_SERVICE"?"Sem recorrência":x.daysUntilExpiration==null?"—":x.daysUntilExpiration<0?`${Math.abs(x.daysUntilExpiration)} dia(s) vencido`:`${x.daysUntilExpiration} dia(s)`}</strong></div></div><div className="icm-actions">{x.documentFilePath&&<button className="icm-btn icm-btn-soft" onClick={()=>download(x)}>Baixar documento</button>}<button className="icm-btn icm-btn-neutral" onClick={()=>edit(x)}>Editar</button><button className="icm-btn icm-btn-danger" onClick={()=>remove(x.id)}>Encerrar/remover</button></div></article>)}</div>}
 </div>;
}
function F({label,full=false,children}){return <div className={`icm-field${full?" icm-field-full":""}`}><label>{label}</label>{children}</div>}
