import { useEffect, useMemo, useState } from "react";
import supplierApi from "../../Services/supplierApi.js";
import "../../styles/infinityModules.css";

const initial={entityType:"COMPANY",legalName:"",tradeName:"",document:"",contactName:"",phone:"",whatsapp:"",email:"",address:"",serviceType:"",notes:"",status:"ACTIVE"};
const entityLabels={COMPANY:"Empresa",INDIVIDUAL:"Pessoa física",FREELANCER:"Autônomo / freelancer"};
const statusLabel={ACTIVE:"Ativo",INACTIVE:"Inativo"};

export default function Fornecedores(){
 const [items,setItems]=useState([]),[form,setForm]=useState(initial),[editingId,setEditingId]=useState(null),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[feedback,setFeedback]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{setItems(await supplierApi.list()??[]);}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível carregar fornecedores e prestadores."});}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>items.filter(x=>{const q=search.trim().toLowerCase();return(!q||[x.legalName,x.tradeName,x.document,x.contactName,x.phone,x.email,x.serviceType,entityLabels[x.entityType]].some(v=>String(v??"").toLowerCase().includes(q)))&&(!status||x.status===status);}),[items,search,status]);
 const metrics=useMemo(()=>({active:items.filter(x=>x.status==="ACTIVE").length,companies:items.filter(x=>(x.entityType??"COMPANY")==="COMPANY").length,independent:items.filter(x=>["INDIVIDUAL","FREELANCER"].includes(x.entityType)).length,contracts:items.reduce((s,x)=>s+(x._count?.contracts??0),0)}),[items]);
 function edit(x){setEditingId(x.id);setForm({...initial,...x,entityType:x.entityType??"COMPANY",document:x.document??"",tradeName:x.tradeName??"",contactName:x.contactName??"",phone:x.phone??"",whatsapp:x.whatsapp??"",email:x.email??"",address:x.address??"",serviceType:x.serviceType??"",notes:x.notes??""});setFeedback(null);window.scrollTo?.({top:0,behavior:"smooth"});}
 function reset(){setEditingId(null);setForm(initial);}
 async function save(e){e.preventDefault();setSaving(true);setFeedback(null);try{const payload={...form,tradeName:form.tradeName||null,document:form.document||null,contactName:form.contactName||null,phone:form.phone||null,whatsapp:form.whatsapp||null,email:form.email||null,address:form.address||null,serviceType:form.serviceType||null,notes:form.notes||null};if(editingId)await supplierApi.update(editingId,payload);else await supplierApi.create(payload);setFeedback({type:"ok",text:editingId?"Cadastro atualizado.":"Fornecedor/prestador cadastrado."});reset();await load();}catch(err){setFeedback({type:"error",text:err?.details?.[0]?.message??err?.message??"Não foi possível salvar o cadastro."});}finally{setSaving(false);}}
 async function remove(id){setFeedback(null);try{await supplierApi.remove(id);setFeedback({type:"ok",text:"Cadastro removido da listagem ativa."});if(editingId===id)reset();await load();}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível remover o cadastro."});}}
 const company=form.entityType==="COMPANY";
 return <div className="icm-page">
  <section className="icm-hero"><div><span className="icm-kicker">🤝 Rede de serviços</span><h1>Fornecedores e profissionais</h1><p>Cadastre empresas, pessoas físicas, autônomos e freelancers que prestam serviços ao condomínio, sem obrigar vínculo empresarial.</p></div><div className="icm-hero-count"><strong>{items.length}</strong><span>cadastros</span></div></section>
  <section className="icm-metrics"><div className="icm-metric"><span>Ativos</span><strong>{metrics.active}</strong></div><div className="icm-metric"><span>Empresas</span><strong>{metrics.companies}</strong></div><div className="icm-metric"><span>PF / freelancers</span><strong>{metrics.independent}</strong></div><div className="icm-metric"><span>Contratos vinculados</span><strong>{metrics.contracts}</strong></div></section>
  {feedback&&<div className={`icm-message icm-message-${feedback.type}`}>{feedback.text}</div>}
  <form className="icm-card icm-form" onSubmit={save}><h2>{editingId?"Editar cadastro":"Novo fornecedor ou profissional"}</h2><div className="icm-form-grid">
   <F label="Tipo de cadastro *"><select className="icm-select" value={form.entityType} onChange={e=>setForm({...form,entityType:e.target.value})}><option value="COMPANY">Empresa</option><option value="INDIVIDUAL">Pessoa física</option><option value="FREELANCER">Autônomo / freelancer</option></select></F>
   <F label={company?"Razão social / nome *":"Nome completo *"}><input className="icm-input" required minLength={2} value={form.legalName} onChange={e=>setForm({...form,legalName:e.target.value})}/></F>
   <F label={company?"Nome fantasia":"Nome profissional / apelido comercial"}><input className="icm-input" value={form.tradeName} onChange={e=>setForm({...form,tradeName:e.target.value})}/></F>
   <F label={company?"CNPJ / documento":"CPF / documento"}><input className="icm-input" value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></F>
   <F label="Tipo de serviço"><input className="icm-input" placeholder="Ex.: Elétrica, hidráulica, elevadores" value={form.serviceType} onChange={e=>setForm({...form,serviceType:e.target.value})}/></F>
   <F label={company?"Contato responsável":"Contato / responsável alternativo"}><input className="icm-input" value={form.contactName} onChange={e=>setForm({...form,contactName:e.target.value})}/></F>
   <F label="Telefone"><input className="icm-input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></F><F label="WhatsApp"><input className="icm-input" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></F>
   <F label="E-mail"><input className="icm-input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></F><F label="Status"><select className="icm-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option></select></F>
   <F label="Endereço" full><input className="icm-input" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></F><F label="Observações" full><textarea className="icm-textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></F>
  </div><div className="icm-actions"><button className="icm-btn icm-btn-primary" disabled={saving}>{saving?"Salvando...":editingId?"Salvar alterações":"Cadastrar"}</button>{editingId&&<button type="button" className="icm-btn icm-btn-neutral" onClick={reset}>Cancelar edição</button>}</div></form>
  <div className="icm-toolbar"><input className="icm-input" placeholder="Buscar por nome, documento, contato ou serviço..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="icm-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option><option value="ACTIVE">Ativos</option><option value="INACTIVE">Inativos</option></select></div>
  {loading?<div className="icm-card icm-empty">Carregando cadastros...</div>:filtered.length===0?<div className="icm-card icm-empty">Nenhum fornecedor ou profissional encontrado.</div>:<div className="icm-table-wrap icm-card"><table className="icm-table"><thead><tr><th>Fornecedor / profissional</th><th>Tipo</th><th>Serviço</th><th>Contato</th><th>Status</th><th>Vínculos</th><th>Ações</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.tradeName||x.legalName}</strong><div className="icm-muted">{x.tradeName?x.legalName:""}{x.document?`${x.tradeName?" · ":""}${x.document}`:""}</div></td><td><span className="icm-pill">{entityLabels[x.entityType??"COMPANY"]}</span></td><td>{x.serviceType||"—"}</td><td>{x.contactName||x.phone||"—"}<div className="icm-muted">{x.email||x.whatsapp||""}</div></td><td><span className={`icm-pill ${x.status==="ACTIVE"?"icm-status-ok":"icm-status-neutral"}`}>{statusLabel[x.status]||x.status}</span></td><td>{x._count?.contracts??0} contrato(s) · {x._count?.assets??0} ativo(s)</td><td><div className="icm-actions"><button className="icm-btn icm-btn-neutral" onClick={()=>edit(x)}>Editar</button><button className="icm-btn icm-btn-danger" onClick={()=>remove(x.id)}>Remover</button></div></td></tr>)}</tbody></table></div>}
 </div>;
}
function F({label,full=false,children}){return <div className={`icm-field${full?" icm-field-full":""}`}><label>{label}</label>{children}</div>}
