import { useEffect, useState } from "react";
import supportTicketApi from "../../Services/supportTicketApi.js";

const STATUS = { OPEN:"Aberta", IN_PROGRESS:"Em atendimento", WAITING_CUSTOMER:"Aguardando cliente", RESOLVED:"Resolvida", CLOSED:"Encerrada" };
const PRIORITY = { LOW:"Baixa", MEDIUM:"Média", HIGH:"Alta", CRITICAL:"Crítica" };

export default function Suporte() {
  const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  const [form,setForm]=useState({title:"",description:"",category:""}); const [saving,setSaving]=useState(false);
  async function load(){setLoading(true);setError("");try{setItems(await supportTicketApi.mine());}catch(e){setError(e?.message??"Não foi possível carregar as solicitações.");}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  async function submit(e){e.preventDefault();setSaving(true);setError("");setSuccess("");try{await supportTicketApi.create(form);setForm({title:"",description:"",category:""});setSuccess("Solicitação de atendimento aberta com sucesso.");await load();}catch(err){setError(err?.message??"Não foi possível abrir a solicitação.");}finally{setSaving(false);}}
  return <div style={s.page}>
    <div style={s.hero}><div><span style={s.kicker}>ATENDIMENTO STAR</span><h1 style={s.title}>Central de Suporte</h1><p style={s.subtitle}>Abra e acompanhe suas solicitações de atendimento em um único lugar.</p></div></div>
    {error&&<div style={s.error}>{error}</div>}{success&&<div style={s.success}>{success}</div>}
    <div style={s.grid}>
      <form onSubmit={submit} style={s.card}><h2 style={s.cardTitle}>Nova solicitação</h2><label style={s.field}>Assunto<input style={s.input} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: dificuldade para acessar relatórios" required /></label><label style={s.field}>Categoria<select style={s.input} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Classificação automática</option><option>ACESSO</option><option>ENCOMENDAS</option><option>RESERVAS</option><option>RELATORIOS</option><option>FINANCEIRO</option><option>GERAL</option></select></label><label style={s.field}>Descrição<textarea style={{...s.input,minHeight:140,paddingTop:12}} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descreva o problema, impacto e o que estava fazendo quando aconteceu." required /></label><button style={s.button} disabled={saving}>{saving?"Enviando...":"Abrir solicitação"}</button></form>
      <div style={s.card}><div style={s.headerRow}><h2 style={s.cardTitle}>Minhas solicitações</h2><button style={s.ghost} onClick={load}>Atualizar</button></div>{loading?<p>Carregando...</p>:items.length===0?<div style={s.empty}>Nenhuma solicitação aberta.</div>:<div style={s.list}>{items.map(i=><div key={i.id} style={s.ticket}><div><strong style={s.ticketTitle}>SA-{String(i.ticketNumber).padStart(5,"0")} · {i.title}</strong><div style={s.meta}>{i.category} · {new Date(i.openedAt).toLocaleString("pt-BR")}</div><p style={s.desc}>{i.description}</p></div><div style={s.badges}><span style={{...s.badge,background:i.priority==="CRITICAL"?"#fee2e2":i.priority==="HIGH"?"#ffedd5":"var(--ic-primary-soft)",color:i.priority==="CRITICAL"?"#991b1b":i.priority==="HIGH"?"#9a3412":"#6b21a8"}}>{PRIORITY[i.priority]??i.priority}</span><span style={s.status}>{STATUS[i.status]??i.status}</span></div></div>)}</div>}</div>
    </div>
  </div>;
}
const s={page:{paddingBottom:30},hero:{padding:"24px",borderRadius:20,background:"linear-gradient(135deg,#3b0764,var(--ic-primary-strong) 65%,var(--ic-primary-light))",color:"white",marginBottom:18,boxShadow:"0 18px 45px rgb(var(--ic-primary-deep-rgb) / .2)"},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.4,opacity:.78},title:{margin:"7px 0 4px",fontSize:"clamp(26px,4vw,38px)"},subtitle:{margin:0,opacity:.86},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,360px),1fr))",gap:18},card:{background:"#fff",border:"1px solid #eee7f7",borderRadius:18,padding:18,boxShadow:"0 10px 30px rgba(55,25,86,.07)"},cardTitle:{margin:"0 0 14px",fontSize:18,color:"#2f1b3d"},field:{display:"grid",gap:6,fontSize:12,fontWeight:800,color:"#5b4a67",marginBottom:12},input:{width:"100%",boxSizing:"border-box",border:"1px solid #ded5e8",borderRadius:11,minHeight:42,padding:"0 11px",font:"inherit",color:"#2f2636",background:"#fff"},button:{width:"100%",border:0,borderRadius:11,padding:"12px 16px",background:"linear-gradient(135deg,var(--ic-primary-dark),var(--ic-primary))",color:"white",fontWeight:900,cursor:"pointer"},ghost:{border:"1px solid #ddd3e8",background:"#fff",borderRadius:10,padding:"8px 11px",color:"var(--ic-primary-strong)",fontWeight:800},headerRow:{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"},list:{display:"grid",gap:10},ticket:{display:"flex",justifyContent:"space-between",gap:14,padding:14,border:"1px solid #eee8f5",borderRadius:13,background:"#fcfaff",flexWrap:"wrap"},ticketTitle:{color:"#352044"},meta:{fontSize:11,color:"#8b7d95",marginTop:4},desc:{fontSize:12,color:"#63566d",margin:"7px 0 0",lineHeight:1.5},badges:{display:"flex",gap:6,alignItems:"flex-start",flexWrap:"wrap"},badge:{padding:"5px 8px",borderRadius:999,fontSize:10,fontWeight:900},status:{padding:"5px 8px",borderRadius:999,fontSize:10,fontWeight:900,background:"var(--ic-primary-soft-2)",color:"var(--ic-primary-dark)"},empty:{padding:28,textAlign:"center",color:"#8b7e95",background:"#faf8fc",borderRadius:12},error:{padding:12,marginBottom:12,borderRadius:10,background:"#fef2f2",color:"#991b1b"},success:{padding:12,marginBottom:12,borderRadius:10,background:"#f0fdf4",color:"#166534"}};
