import { useEffect, useMemo, useState } from "react";
import { FaHeadset, FaPlus, FaTimes } from "react-icons/fa";
import supportTicketApi from "../Services/supportTicketApi.js";

const priorityStyle = { CRITICA:["#fee2e2","#991b1b"], ALTA:["#ffedd5","#9a3412"], MEDIA:["#fef3c7","#92400e"], BAIXA:["#e0f2fe","#075985"] };
const statusLabel = { ABERTA:"Aberta", EM_ATENDIMENTO:"Em atendimento", AGUARDANDO_CLIENTE:"Aguardando cliente", RESOLVIDA:"Resolvida", ENCERRADA:"Encerrada" };

function SupportCenter(){
  const [items,setItems]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState(""), [modal,setModal]=useState(false), [saving,setSaving]=useState(false);
  const [form,setForm]=useState({subject:"",description:"",impact:""});
  async function load(){setLoading(true);setError("");try{const data=await supportTicketApi.list("?mine=true");setItems(Array.isArray(data)?data:[]);}catch(e){setError(e?.message??"Não foi possível carregar o suporte.");}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  const openCount=useMemo(()=>items.filter(i=>!["RESOLVIDA","ENCERRADA"].includes(i.status)).length,[items]);
  async function submit(e){e.preventDefault();setSaving(true);setError("");try{await supportTicketApi.create(form);setForm({subject:"",description:"",impact:""});setModal(false);await load();}catch(err){setError(err?.message??"Não foi possível abrir a solicitação.");}finally{setSaving(false);}}
  return <div style={s.page}>
    <section style={s.hero} className="pilot-hero"><div><span style={s.kicker}>SUPORTE STAR INFINITY CODE</span><h1 style={s.title}>Central de Atendimento</h1><p style={s.subtitle}>Abra uma solicitação e acompanhe o protocolo, prioridade e andamento em um único lugar.</p></div><div style={s.heroStat}><FaHeadset/><strong>{openCount}</strong><span>em andamento</span></div></section>
    {error&&<div style={s.error}>{error}</div>}
    <div style={s.toolbar}><h2 style={s.sectionTitle}>Minhas solicitações</h2><button style={s.primary} type="button" onClick={()=>setModal(true)}><FaPlus/> Nova solicitação</button></div>
    {loading?<div style={s.empty}>Carregando...</div>:items.length===0?<div style={s.empty}>Você ainda não abriu solicitações.</div>:<div style={s.grid}>{items.map(item=>{const ps=priorityStyle[item.priority]||priorityStyle.MEDIA;return <article key={item.id} style={s.card}>
      <div style={s.cardTop}><span style={s.code}>{item.code}</span><span style={{...s.badge,background:ps[0],color:ps[1]}}>{item.priority}</span></div>
      <h3 style={s.cardTitle}>{item.subject}</h3><p style={s.description}>{item.description}</p>
      <div style={s.meta}><span>{item.category}</span><strong>{statusLabel[item.status]||item.status}</strong><span>{new Date(item.createdAt).toLocaleString("pt-BR")}</span></div>
      {item.response&&<div style={s.response}><strong>Resposta da Central</strong><p>{item.response}</p></div>}
    </article>})}</div>}
    {modal&&<div style={s.overlay} onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form style={s.modal} onSubmit={submit}><div style={s.modalHead}><div><span style={s.kicker}>NOVA SA</span><h2 style={s.modalTitle}>Abrir solicitação</h2></div><button type="button" style={s.close} onClick={()=>setModal(false)}><FaTimes/></button></div>
      <label style={s.field}><span>Assunto *</span><input required minLength={4} maxLength={120} style={s.input} value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Ex.: Não consigo acessar o módulo de reservas"/></label>
      <label style={s.field}><span>Descrição *</span><textarea required minLength={10} maxLength={2000} style={{...s.input,minHeight:130,resize:"vertical"}} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Explique o que aconteceu, desde quando e quem foi afetado."/></label>
      <label style={s.field}><span>Impacto</span><select style={s.input} value={form.impact} onChange={e=>setForm({...form,impact:e.target.value})}><option value="">Selecione</option><option value="Apenas eu">Apenas eu</option><option value="Alguns usuários">Alguns usuários</option><option value="Toda a operação">Toda a operação</option></select></label>
      <div style={s.actions}><button type="button" style={s.secondary} onClick={()=>setModal(false)}>Cancelar</button><button disabled={saving} style={s.primary}>{saving?"Enviando...":"Abrir solicitação"}</button></div>
    </form></div>}
  </div>
}
const s={page:{display:"grid",gap:18},hero:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,padding:26,borderRadius:26,background:"linear-gradient(135deg,#2e1065,#6d28d9 58%,#8b5cf6)",color:"white",boxShadow:"0 24px 60px rgba(76,29,149,.22)"},kicker:{fontSize:10,fontWeight:900,letterSpacing:1.5,opacity:.82},title:{margin:"7px 0",fontSize:"clamp(26px,4vw,38px)"},subtitle:{margin:0,maxWidth:720,color:"rgba(255,255,255,.82)",lineHeight:1.6},heroStat:{minWidth:120,padding:16,borderRadius:20,background:"rgba(255,255,255,.12)",display:"grid",placeItems:"center",gap:5,border:"1px solid rgba(255,255,255,.18)"},toolbar:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"},sectionTitle:{margin:0,color:"#2e174f"},primary:{border:0,borderRadius:13,padding:"12px 16px",background:"linear-gradient(135deg,#6d28d9,#8b5cf6)",color:"white",fontWeight:850,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:8},secondary:{border:"1px solid #ddd6fe",borderRadius:13,padding:"12px 16px",background:"white",color:"#5b21b6",fontWeight:800,cursor:"pointer"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14},card:{background:"white",border:"1px solid #ede9fe",borderRadius:20,padding:18,boxShadow:"0 12px 34px rgba(76,29,149,.07)"},cardTop:{display:"flex",justifyContent:"space-between",gap:10},code:{fontSize:11,fontWeight:900,color:"#7c3aed",letterSpacing:.6},badge:{padding:"6px 9px",borderRadius:999,fontSize:10,fontWeight:900},cardTitle:{color:"#2e174f",margin:"12px 0 8px"},description:{color:"#6b7280",fontSize:13,lineHeight:1.6},meta:{display:"flex",gap:10,flexWrap:"wrap",fontSize:11,color:"#7c6b95",marginTop:14},response:{marginTop:14,padding:13,borderRadius:14,background:"#f5f3ff",color:"#4c1d95",fontSize:13,lineHeight:1.5},empty:{padding:30,borderRadius:18,background:"white",border:"1px dashed #d8ccf3",color:"#6b7280",textAlign:"center"},error:{padding:12,borderRadius:12,background:"#fef2f2",color:"#b91c1c",border:"1px solid #fecaca"},overlay:{position:"fixed",inset:0,background:"rgba(23,10,45,.58)",backdropFilter:"blur(6px)",display:"grid",placeItems:"center",padding:16,zIndex:1000},modal:{width:"min(620px,100%)",background:"white",borderRadius:24,padding:22,boxShadow:"0 30px 90px rgba(0,0,0,.28)"},modalHead:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12},modalTitle:{margin:"5px 0 0",color:"#2e174f"},close:{width:38,height:38,border:0,borderRadius:12,background:"#f5f3ff",color:"#6d28d9",cursor:"pointer"},field:{display:"grid",gap:7,marginTop:16,color:"#5b4b67",fontSize:12,fontWeight:850},input:{width:"100%",boxSizing:"border-box",padding:"12px 13px",borderRadius:12,border:"1px solid #ddd6fe",outline:"none",fontFamily:"inherit"},actions:{display:"flex",justifyContent:"flex-end",gap:9,marginTop:20,flexWrap:"wrap"}};
export default SupportCenter;
