import { useEffect, useMemo, useState } from "react";
import { FaExclamationTriangle, FaHeadset, FaSyncAlt } from "react-icons/fa";
import platformApi from "../../Services/platformApi.js";
import PlatformSupport from "./PlatformSupport.jsx";
import { PlatformCard, PlatformError, PlatformLoading, PlatformPageHeader } from "../../components/PlatformUi.jsx";

const priorityColor={CRITICA:["#fee2e2","#991b1b"],ALTA:["#ffedd5","#9a3412"],MEDIA:["#fef3c7","#92400e"],BAIXA:["#e0f2fe","#075985"]};
function PlatformSupportDesk(){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");
  const [replyTarget,setReplyTarget]=useState(null),[replyText,setReplyText]=useState("");
  async function load(){setLoading(true);setError("");try{setData(await platformApi.supportTickets.list());}catch(e){setError(e?.message??"Não foi possível carregar as solicitações.");}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  const items=useMemo(()=>data?.items??[],[data]); const summary=data?.summary??{};
  async function update(id,payload){setBusy(id);setError("");try{await platformApi.supportTickets.update(id,payload);await load();}catch(e){setError(e?.message??"Não foi possível atualizar a solicitação.");}finally{setBusy("");}}
  return <div style={s.page}><PlatformPageHeader eyebrow="SUPORTE E OPERAÇÃO" title="Solicitações de Atendimento" description="Fila priorizada automaticamente, organizada por cliente, impacto, categoria e tempo em aberto."/><PlatformError message={error}/>
    <div style={s.metrics}>{[["Abertas",summary.open??0],["Críticas",summary.critical??0],["Altas",summary.high??0],["Total",summary.total??0]].map(([l,v])=><PlatformCard key={l}><span style={s.label}>{l}</span><strong style={s.value}>{v}</strong></PlatformCard>)}</div>
    {loading?<PlatformLoading text="Carregando SAs..."/>:<PlatformCard><div style={s.head}><div><span style={s.kicker}>FILA DE ATENDIMENTO</span><h3 style={s.title}>Prioridade operacional</h3></div><button type="button" style={s.refresh} onClick={load}><FaSyncAlt/> Atualizar</button></div>{items.length===0?<div style={s.empty}>Nenhuma solicitação aberta.</div>:<div style={s.list}>{items.map(item=>{const pc=priorityColor[item.priority]||priorityColor.MEDIA;return <article key={item.id} style={s.ticket}><div style={s.ticketTop}><div><span style={s.code}>{item.code}</span><h4 style={s.subject}>{item.subject}</h4><span style={s.client}>{item.condominium?.name} • {item.openedBy?.name}</span></div><span style={{...s.badge,background:pc[0],color:pc[1]}}>{item.priority}</span></div><p style={s.desc}>{item.description}</p><div style={s.ticketMeta}><span>{item.category}</span><span>{new Date(item.createdAt).toLocaleString("pt-BR")}</span><strong>{item.status}</strong></div><div style={s.actions}><select style={s.select} value={item.priority} onChange={e=>update(item.id,{priority:e.target.value})} disabled={busy===item.id}><option>CRITICA</option><option>ALTA</option><option>MEDIA</option><option>BAIXA</option></select><select style={s.select} value={item.status} onChange={e=>update(item.id,{status:e.target.value})} disabled={busy===item.id}><option>ABERTA</option><option>EM_ATENDIMENTO</option><option>AGUARDANDO_CLIENTE</option><option>RESOLVIDA</option><option>ENCERRADA</option></select><button type="button" style={s.answer} onClick={()=>{setReplyTarget(item);setReplyText(item.response??"");}} disabled={busy===item.id}><FaHeadset/> Responder</button></div>{item.response&&<div style={s.response}><strong>Resposta registrada:</strong> {item.response}</div>}</article>})}</div>}</PlatformCard>}
    {replyTarget&&<div style={s.overlay} onMouseDown={e=>e.target===e.currentTarget&&setReplyTarget(null)}><div style={s.modal}><div style={s.modalHead}><div><span style={s.kicker}>RESPOSTA AO CLIENTE</span><h3 style={s.modalTitle}>{replyTarget.code} • {replyTarget.subject}</h3></div><button type="button" style={s.close} onClick={()=>setReplyTarget(null)}>×</button></div><textarea style={s.textarea} value={replyText} onChange={e=>setReplyText(e.target.value)} placeholder="Escreva a orientação ou retorno para o cliente."/><div style={s.modalActions}><button type="button" style={s.cancel} onClick={()=>setReplyTarget(null)}>Cancelar</button><button type="button" style={s.answer} disabled={busy===replyTarget.id||replyText.trim().length<2} onClick={async()=>{await update(replyTarget.id,{response:replyText,status:replyTarget.status==="ABERTA"?"EM_ATENDIMENTO":replyTarget.status});setReplyTarget(null);}}>Salvar resposta</button></div></div></div>}
    <div style={s.sessionTitle}><FaExclamationTriangle/><div><strong>Sessões técnicas rastreáveis</strong><span> Mantidas para atendimentos que exijam acesso administrativo ao contexto do cliente.</span></div></div><PlatformSupport/></div>
}
const s={page:{display:"grid",gap:18},metrics:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12},label:{display:"block",fontSize:11,fontWeight:850,color:"#756d7d"},value:{display:"block",fontSize:28,color:"#4c1d95",marginTop:8},head:{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:14},kicker:{fontSize:10,fontWeight:900,letterSpacing:1.4,color:"#7c3aed"},title:{margin:"5px 0",color:"#2e174f"},refresh:{border:"1px solid #ddd6fe",borderRadius:12,padding:"10px 13px",background:"white",color:"#6d28d9",fontWeight:800,cursor:"pointer",display:"inline-flex",gap:7,alignItems:"center"},list:{display:"grid",gap:12},ticket:{padding:17,borderRadius:18,border:"1px solid #eee8fb",background:"linear-gradient(135deg,#fff,#fcfaff)"},ticketTop:{display:"flex",justifyContent:"space-between",gap:12},code:{color:"#7c3aed",fontSize:10,fontWeight:900,letterSpacing:.8},subject:{margin:"5px 0",color:"#2e174f"},client:{fontSize:12,color:"#756d7d"},badge:{padding:"7px 10px",height:"fit-content",borderRadius:999,fontSize:10,fontWeight:900},desc:{color:"#6b7280",fontSize:13,lineHeight:1.55},ticketMeta:{display:"flex",gap:12,flexWrap:"wrap",fontSize:11,color:"#7c6b95",margin:"12px 0"},actions:{display:"flex",gap:8,flexWrap:"wrap"},select:{padding:"10px",borderRadius:11,border:"1px solid #ddd6fe",background:"white",color:"#4c1d95"},answer:{border:0,borderRadius:11,padding:"10px 13px",background:"linear-gradient(135deg,#6d28d9,#8b5cf6)",color:"white",fontWeight:800,cursor:"pointer",display:"inline-flex",gap:7,alignItems:"center"},response:{marginTop:12,padding:12,borderRadius:12,background:"#f5f3ff",color:"#4c1d95",fontSize:12},empty:{padding:28,textAlign:"center",color:"#6b7280"},overlay:{position:"fixed",inset:0,background:"rgba(23,10,45,.62)",backdropFilter:"blur(6px)",display:"grid",placeItems:"center",padding:16,zIndex:1200},modal:{width:"min(620px,100%)",background:"white",borderRadius:22,padding:20,boxShadow:"0 30px 90px rgba(0,0,0,.3)"},modalHead:{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"},modalTitle:{margin:"5px 0",color:"#2e174f"},close:{width:36,height:36,border:0,borderRadius:10,background:"#f5f3ff",color:"#6d28d9",fontSize:22,cursor:"pointer"},textarea:{width:"100%",minHeight:140,boxSizing:"border-box",resize:"vertical",border:"1px solid #ddd6fe",borderRadius:13,padding:12,outline:"none",fontFamily:"inherit",marginTop:12},modalActions:{display:"flex",justifyContent:"flex-end",gap:8,marginTop:14,flexWrap:"wrap"},cancel:{border:"1px solid #ddd6fe",borderRadius:11,padding:"10px 13px",background:"white",color:"#5b21b6",fontWeight:800,cursor:"pointer"},sessionTitle:{display:"flex",gap:10,alignItems:"center",padding:14,borderRadius:14,background:"#fff7ed",color:"#9a3412",fontSize:12}};
export default PlatformSupportDesk;
