import { useEffect, useMemo, useState } from "react";
import { FaDatabase, FaSave, FaShieldAlt, FaTimes, FaTrashAlt } from "react-icons/fa";
import platformApi from "../../Services/platformApi.js";
import { PlatformCard, PlatformError, PlatformLoading, PlatformPageHeader } from "../../components/PlatformUi.jsx";

const labels = {condominiums:"Condomínios",users:"Usuários",apartments:"Apartamentos",residents:"Moradores",doormen:"Porteiros",visitors:"Visitantes",packages:"Encomendas",reservations:"Reservas",occurrences:"Ocorrências",expenses:"Despesas",charges:"Cobranças",supportTickets:"Solicitações",auditLogs:"Auditoria",backups:"Backups"};

function PlatformDatabase(){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState(""),[modal,setModal]=useState(false),[confirmation,setConfirmation]=useState(""),[busy,setBusy]=useState(false);
  async function load(){setLoading(true);setError("");try{setData(await platformApi.operations.databaseOverview());}catch(e){setError(e?.message??"Não foi possível carregar o ambiente.");}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  const counts=useMemo(()=>Object.entries(data?.counts??{}),[data]);
  async function backup(){setBusy(true);setError("");setSuccess("");try{await platformApi.operations.createBackup();setSuccess("Backup criado e registrado com sucesso.");await load();}catch(e){setError(e?.message??"Não foi possível gerar o backup.");}finally{setBusy(false);}}
  async function reset(){setBusy(true);setError("");setSuccess("");try{await platformApi.operations.resetHomologation(confirmation);setModal(false);setConfirmation("");setSuccess("Ambiente de homologação zerado. Um backup foi criado antes da limpeza.");await load();}catch(e){setError(e?.message??"Não foi possível zerar o ambiente.");}finally{setBusy(false);}}
  if(loading&&!data)return <PlatformLoading text="Carregando visão do banco..."/>;
  return <div style={s.page}>
    <PlatformPageHeader eyebrow="CONTROLE DO AMBIENTE" title="Banco e Homologação" description="Visão segura dos dados operacionais, backups e ferramentas de limpeza do ambiente de testes."/>
    <PlatformError message={error}/>{success&&<div style={s.success}>{success}</div>}
    <section style={s.hero} className="pilot-hero"><div><span style={s.kicker}>AMBIENTE</span><h2 style={s.heroTitle}>{String(data?.environment??"development").toUpperCase()}</h2><p style={s.heroText}>A Central exibe contagens e ações controladas; nenhuma tabela crua do PostgreSQL é exposta ao navegador.</p></div><div style={s.heroIcon}><FaDatabase/></div></section>
    <div style={s.grid}>{counts.map(([key,value])=><PlatformCard key={key}><span style={s.label}>{labels[key]??key}</span><strong style={s.value}>{value}</strong></PlatformCard>)}</div>
    <div style={s.two} className="pilot-two-col"><PlatformCard><div style={s.cardHead}><div><span style={s.kicker}>PROTEÇÃO</span><h3 style={s.cardTitle}>Backup manual</h3></div><FaSave/></div><p style={s.text}>Gera um dump físico do PostgreSQL e mantém o registro no histórico da Central.</p><button type="button" style={s.primary} onClick={backup} disabled={busy}>{busy?"Processando...":"Criar backup agora"}</button></PlatformCard>
      <PlatformCard><div style={s.cardHead}><div><span style={s.kicker}>HOMOLOGAÇÃO</span><h3 style={s.cardTitle}>Zerar dados de teste</h3></div><FaShieldAlt/></div><p style={s.text}>Preserva o PLATFORM_OWNER, os planos, as features, migrations e backups. Clientes e dados operacionais são removidos após backup automático.</p>{data?.canReset?<button type="button" style={s.danger} onClick={()=>setModal(true)}><FaTrashAlt/> Zerar homologação</button>:<span style={s.prodLock}>Bloqueado em produção</span>}</PlatformCard></div>
    {modal&&<div style={s.overlay} onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><div style={s.modal}><div style={s.modalHead}><div><span style={s.kicker}>AÇÃO DE ALTO IMPACTO</span><h2 style={s.modalTitle}>Zerar ambiente de homologação</h2></div><button style={s.close} type="button" onClick={()=>setModal(false)}><FaTimes/></button></div><p style={s.text}>Um backup será criado antes da limpeza. Para confirmar, digite exatamente <strong>ZERAR HOMOLOGACAO</strong>.</p><input style={s.input} value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="ZERAR HOMOLOGACAO"/><div style={s.actions}><button style={s.secondary} onClick={()=>setModal(false)} type="button">Cancelar</button><button style={s.danger} type="button" disabled={busy||confirmation.trim().toUpperCase()!=="ZERAR HOMOLOGACAO"} onClick={reset}>{busy?"Zerando...":"Confirmar limpeza"}</button></div></div></div>}
  </div>
}
const s={page:{display:"grid",gap:18},hero:{display:"flex",alignItems:"center",justifyContent:"space-between",gap:20,padding:26,borderRadius:26,background:"linear-gradient(135deg,#2e1065,#5b21b6 58%,#8b5cf6)",color:"white",boxShadow:"0 24px 60px rgba(76,29,149,.2)"},kicker:{fontSize:10,fontWeight:900,letterSpacing:1.5,color:"#8b5cf6"},heroTitle:{margin:"6px 0",fontSize:30},heroText:{margin:0,maxWidth:720,color:"rgba(255,255,255,.82)",lineHeight:1.6},heroIcon:{width:70,height:70,borderRadius:22,display:"grid",placeItems:"center",fontSize:28,background:"rgba(255,255,255,.12)",border:"1px solid rgba(255,255,255,.18)"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12},label:{display:"block",color:"#756d7d",fontSize:11,fontWeight:800},value:{display:"block",marginTop:8,fontSize:27,color:"#4c1d95"},two:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16},cardHead:{display:"flex",justifyContent:"space-between",alignItems:"center",color:"#6d28d9"},cardTitle:{margin:"5px 0",color:"#2e174f"},text:{color:"#6b7280",lineHeight:1.6,fontSize:13},primary:{border:0,borderRadius:13,padding:"12px 16px",background:"linear-gradient(135deg,#6d28d9,#8b5cf6)",color:"white",fontWeight:850,cursor:"pointer"},danger:{border:0,borderRadius:13,padding:"12px 16px",background:"#b91c1c",color:"white",fontWeight:850,cursor:"pointer",display:"inline-flex",gap:8,alignItems:"center"},secondary:{border:"1px solid #ddd6fe",borderRadius:13,padding:"12px 16px",background:"white",color:"#5b21b6",fontWeight:800,cursor:"pointer"},success:{padding:12,borderRadius:12,background:"#ecfdf5",color:"#047857",border:"1px solid #a7f3d0"},prodLock:{display:"inline-block",padding:"9px 12px",borderRadius:999,background:"#f3f4f6",color:"#6b7280",fontWeight:800,fontSize:12},overlay:{position:"fixed",inset:0,background:"rgba(23,10,45,.62)",display:"grid",placeItems:"center",padding:16,zIndex:1000,backdropFilter:"blur(7px)"},modal:{width:"min(560px,100%)",background:"white",borderRadius:24,padding:22,boxShadow:"0 30px 90px rgba(0,0,0,.3)"},modalHead:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12},modalTitle:{margin:"5px 0",color:"#2e174f"},close:{width:38,height:38,border:0,borderRadius:12,background:"#f5f3ff",color:"#6d28d9",cursor:"pointer"},input:{width:"100%",boxSizing:"border-box",padding:"13px",borderRadius:12,border:"1px solid #ddd6fe",outline:"none",marginTop:8},actions:{display:"flex",justifyContent:"flex-end",gap:9,marginTop:18,flexWrap:"wrap"}};
export default PlatformDatabase;
