import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FaBuilding, FaChartLine, FaExclamationCircle, FaHeadset, FaMoneyBillWave, FaUsers } from "react-icons/fa";
import platformApi from "../../Services/platformApi.js";
import { PlatformCard, PlatformError, PlatformLoading, PlatformPageHeader } from "../../components/PlatformUi.jsx";

const money=c=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(c||0)/100);
function PlatformDashboardExecutive(){
  const [state,setState]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const [dashboard,clients,support,charges]=await Promise.all([platformApi.dashboard.get(),platformApi.condominiums.clients("?limit=100"),platformApi.supportTickets.list(),platformApi.finance.allCharges()]);setState({dashboard,clients,support,charges});}catch(e){setError(e?.message??"Não foi possível carregar o dashboard executivo.");}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  const summary=state?.clients?.summary??{}; const support=state?.support?.summary??{}; const charges=state?.charges??[];
  const paid=charges.filter(c=>c.status==="PAID").reduce((a,c)=>a+Number(c.amountInCents||0),0); const pending=charges.filter(c=>["PENDING","OVERDUE"].includes(c.status)).reduce((a,c)=>a+Number(c.amountInCents||0),0);
  const monthData=useMemo(()=>{const map=new Map();for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;map.set(key,{key,label:d.toLocaleDateString("pt-BR",{month:"short"}),receita:0,cobrancas:0});}charges.forEach(c=>{if(c.status!=="PAID")return;const d=new Date(c.paidAt||c.updatedAt||c.createdAt);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;if(map.has(key)){const x=map.get(key);x.receita+=Number(c.amountInCents||0)/100;x.cobrancas+=1;}});return [...map.values()];},[charges]);
  const planData=[{name:"Básico",value:summary.basicClients??0},{name:"Completo",value:summary.completeClients??0}];
  const statusData=[{name:"Pagas",value:charges.filter(c=>c.status==="PAID").length},{name:"Pendentes",value:charges.filter(c=>c.status==="PENDING").length},{name:"Vencidas",value:charges.filter(c=>c.status==="OVERDUE").length}];
  if(loading&&!state)return <PlatformLoading text="Carregando dashboard executivo..."/>;
  return <div style={s.page}><PlatformPageHeader eyebrow="CENTRAL EXECUTIVA" title="Dashboard Star Infinity Code" description="Visão consolidada de clientes, receita, cobrança, suporte e crescimento da operação."/><PlatformError message={error}/>
    <section style={s.hero} className="pilot-hero"><div><span style={s.heroK}>VISÃO DO NEGÓCIO</span><h2 style={s.heroTitle}>{money(summary.estimatedMonthlyRevenueInCents)}</h2><p style={s.heroText}>MRR estimado da carteira ativa</p></div><div style={s.heroCards}><HeroMini icon={<FaBuilding/>} label="Clientes ativos" value={summary.activeClients??0}/><HeroMini icon={<FaHeadset/>} label="SAs abertas" value={support.open??0}/><HeroMini icon={<FaExclamationCircle/>} label="SAs críticas" value={support.critical??0}/></div></section>
    <div style={s.metrics}><Metric icon={<FaMoneyBillWave/>} label="Receita recebida" value={money(paid)}/><Metric icon={<FaChartLine/>} label="A receber" value={money(pending)}/><Metric icon={<FaUsers/>} label="Novos no mês" value={summary.newThisMonth??0}/><Metric icon={<FaBuilding/>} label="Plano Completo" value={summary.completeClients??0}/></div>
    <div style={s.charts} className="pilot-two-col"><PlatformCard><h3 style={s.cardTitle}>Receita recebida • 6 meses</h3><div style={s.chart}><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthData}><defs><linearGradient id="rev" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#7c3aed" stopOpacity={.35}/><stop offset="95%" stopColor="#7c3aed" stopOpacity={.02}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v)}/><Area type="monotone" dataKey="receita" stroke="#7c3aed" fill="url(#rev)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></PlatformCard>
      <PlatformCard><h3 style={s.cardTitle}>Carteira por plano</h3><div style={s.chart}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={planData} dataKey="value" nameKey="name" innerRadius={58} outerRadius={90} paddingAngle={5}>{planData.map((_,i)=><Cell key={i} fill={i===0?"#a78bfa":"#5b21b6"}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div style={s.legend}><span>● Básico {summary.basicClients??0}</span><span>● Completo {summary.completeClients??0}</span></div></PlatformCard></div>
    <PlatformCard><h3 style={s.cardTitle}>Saúde das cobranças</h3><div style={s.chartSmall}><ResponsiveContainer width="100%" height="100%"><BarChart data={statusData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" radius={[10,10,0,0]} fill="#6d28d9"/></BarChart></ResponsiveContainer></div></PlatformCard>
  </div>
}
function Metric({icon,label,value}){return <div style={s.metric}><div style={s.metricIcon}>{icon}</div><div><span style={s.metricLabel}>{label}</span><strong style={s.metricValue}>{value}</strong></div></div>}
function HeroMini({icon,label,value}){return <div style={s.heroMini}><span>{icon}</span><strong>{value}</strong><small>{label}</small></div>}
const s={page:{display:"grid",gap:18},hero:{padding:28,borderRadius:28,background:"radial-gradient(circle at top right,rgba(196,181,253,.35),transparent 30%),linear-gradient(135deg,#241047,#5b21b6 55%,#7c3aed)",color:"white",display:"grid",gridTemplateColumns:"1fr auto",gap:22,alignItems:"center",boxShadow:"0 28px 70px rgba(76,29,149,.24)"},heroK:{fontSize:10,fontWeight:900,letterSpacing:1.7,opacity:.75},heroTitle:{fontSize:"clamp(36px,6vw,58px)",margin:"7px 0 0"},heroText:{margin:"4px 0 0",color:"rgba(255,255,255,.75)"},heroCards:{display:"grid",gridTemplateColumns:"repeat(3,120px)",gap:10},heroMini:{padding:14,borderRadius:18,background:"rgba(255,255,255,.11)",border:"1px solid rgba(255,255,255,.16)",display:"grid",gap:4,textAlign:"center"},metrics:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:13},metric:{display:"flex",gap:13,alignItems:"center",padding:17,borderRadius:19,background:"white",border:"1px solid #ede9fe",boxShadow:"0 12px 34px rgba(76,29,149,.07)"},metricIcon:{width:43,height:43,borderRadius:14,display:"grid",placeItems:"center",background:"#f5f3ff",color:"#6d28d9"},metricLabel:{display:"block",fontSize:11,color:"#756d7d",fontWeight:800},metricValue:{display:"block",fontSize:19,color:"#2e174f",marginTop:3},charts:{display:"grid",gridTemplateColumns:"1.4fr .8fr",gap:16},cardTitle:{margin:"0 0 14px",color:"#2e174f"},chart:{height:280},chartSmall:{height:220},legend:{display:"flex",justifyContent:"center",gap:20,color:"#6b7280",fontSize:12}};
export default PlatformDashboardExecutive;
