import { useEffect, useState } from "react";
import QRCode from "qrcode";
import visitorApi from "../../Services/visitorApi.js";
import "../../styles/infinityModules.css";

const initial={name:"",document:"",phone:"",visitType:"Visita",notes:"",validFrom:"",validUntil:""};
const labels={WAITING:"Aguardando",AUTHORIZED:"Autorizado",USED:"Utilizado",EXPIRED:"Expirado",CANCELED:"Cancelado"};
const localIso=value=>value?new Date(value).toISOString():"";
export default function VisitantesMorador(){
 const [items,setItems]=useState([]),[form,setForm]=useState(initial),[feedback,setFeedback]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[issued,setIssued]=useState(null);
 async function load(){setLoading(true);try{setItems(await visitorApi.myInvitations());}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível carregar os convites."});}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function save(e){e.preventDefault();setFeedback(null);setIssued(null);setSaving(true);try{const created=await visitorApi.createInvitation({...form,validFrom:localIso(form.validFrom),validUntil:localIso(form.validUntil),document:form.document||null,phone:form.phone||null,visitType:form.visitType||null,notes:form.notes||null});const token=created?.credential?.qrToken;if(!token)throw new Error("O servidor não retornou a credencial do QR.");const qrDataUrl=await QRCode.toDataURL(token,{width:420,margin:2,errorCorrectionLevel:"M"});setIssued({token,qrDataUrl,visitor:created});setForm(initial);setFeedback({type:"ok",text:"Convite criado. Compartilhe ou salve o QR agora; por segurança a credencial não é exibida novamente depois de recarregar a página."});await load();}catch(err){setFeedback({type:"error",text:err?.details?.[0]?.message??err?.message??"Não foi possível criar o convite."});}finally{setSaving(false);}}
 async function cancel(id){try{await visitorApi.cancelInvitation(id);setFeedback({type:"ok",text:"Convite cancelado."});await load();}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível cancelar o convite."});}}
 async function share(){if(!issued)return;try{if(navigator.share){await navigator.share({title:`Convite InfinityCondo - ${issued.visitor.name}`,text:`QR de acesso do visitante ${issued.visitor.name}. Credencial: ${issued.token}`});}else{await navigator.clipboard.writeText(issued.token);setFeedback({type:"ok",text:"Código do convite copiado. Compartilhe-o somente com o visitante autorizado."});}}catch(e){if(e?.name!=="AbortError")setFeedback({type:"error",text:"Não foi possível compartilhar. Use o QR exibido na tela."});}}
 return <div className="icm-page"><section className="icm-hero"><div><span className="icm-kicker">🎟️ Autorização antecipada</span><h1>Convites de visitantes</h1><p>Autorize um visitante para uma janela de horário específica e gere um QR único para validação na portaria.</p></div><div className="icm-hero-count"><strong>{items.length}</strong><span>convites</span></div></section>{feedback&&<div className={`icm-message icm-message-${feedback.type}`}>{feedback.text}</div>}
 {issued&&<section className="icm-card icm-form"><h2>QR criado para {issued.visitor.name}</h2><div className="icm-qr-wrap"><img className="icm-qr" src={issued.qrDataUrl} alt={`QR de acesso de ${issued.visitor.name}`}/><div><p className="icm-subtle">A portaria valida este QR diretamente no backend. Ele só funciona no seu condomínio, dentro do período autorizado, uma única vez e deixa de funcionar após uso, cancelamento ou expiração.</p><button className="icm-btn icm-btn-primary" onClick={share}>Compartilhar convite</button></div></div></section>}
 <form className="icm-card icm-form" onSubmit={save}><h2>Novo convite</h2><div className="icm-form-grid"><F label="Nome do visitante *"><input className="icm-input" required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></F><F label="Documento"><input className="icm-input" value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></F><F label="Telefone"><input className="icm-input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></F><F label="Tipo de visita"><input className="icm-input" value={form.visitType} onChange={e=>setForm({...form,visitType:e.target.value})}/></F><F label="Válido a partir de *"><input className="icm-input" type="datetime-local" required value={form.validFrom} onChange={e=>setForm({...form,validFrom:e.target.value})}/></F><F label="Válido até *"><input className="icm-input" type="datetime-local" required value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></F><F label="Observações" full><textarea className="icm-textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></F></div><div className="icm-actions"><button className="icm-btn icm-btn-primary" disabled={saving}>{saving?"Gerando...":"Gerar convite e QR"}</button></div></form>
 <h2 className="icm-section-title">Meus convites</h2>{loading?<div className="icm-card icm-empty">Carregando convites...</div>:items.length===0?<div className="icm-card icm-empty">Você ainda não criou convites.</div>:<div className="icm-grid">{items.map(x=><article className="icm-card" key={x.id}><h3>{x.name}</h3><div className="icm-meta"><span className={`icm-pill ${x.status==="USED"?"icm-status-ok":["EXPIRED","CANCELED"].includes(x.status)?"icm-status-neutral":"icm-status-warning"}`}>{labels[x.status]||x.status}</span><span className="icm-pill">Apto {x.apartment?.number||x.apartment?.unit||"—"}</span></div><div className="icm-detail-grid"><div><span>Início</span><strong>{x.validFrom?new Date(x.validFrom).toLocaleString("pt-BR"):"—"}</strong></div><div><span>Fim</span><strong>{x.validUntil?new Date(x.validUntil).toLocaleString("pt-BR"):"—"}</strong></div></div>{["WAITING","AUTHORIZED"].includes(x.status)&&<div className="icm-actions"><button className="icm-btn icm-btn-danger" onClick={()=>cancel(x.id)}>Cancelar convite</button></div>}</article>)}</div>}</div>;
}
function F({label,full=false,children}){return <div className={`icm-field${full?" icm-field-full":""}`}><label>{label}</label>{children}</div>}
