import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import residentApi from "../Services/residentApi.js";
import apartmentApi from "../Services/apartmentApi.js";
import visitorApi from "../Services/visitorApi.js";
import packageApi from "../Services/packageApi.js";
import occurrenceApi from "../Services/occurrenceApi.js";

function textOf(...values){return values.filter(Boolean).join(" ").toLowerCase();}
function labelApartment(item){return [item.block??item.bloco,item.number??item.numero].filter(Boolean).join(" / ")||"Apartamento";}

export default function GlobalSearch(){
 const [q,setQ]=useState(""); const [items,setItems]=useState([]); const [loading,setLoading]=useState(false); const [open,setOpen]=useState(false); const timer=useRef(null); const navigate=useNavigate();
 useEffect(()=>{window.clearTimeout(timer.current); if(q.trim().length<2){setItems([]);setOpen(false);return;} timer.current=window.setTimeout(async()=>{setLoading(true);try{const [residents,apartments,visitors,packages,occurrences]=await Promise.all([residentApi.list(),apartmentApi.list(),visitorApi.list(),packageApi.list(),occurrenceApi.list()]); const needle=q.trim().toLowerCase(); const all=[
 ...(residents??[]).filter(x=>textOf(x.user?.name,x.name,x.nome,x.user?.email,x.apartment?.number,x.apartamento).includes(needle)).slice(0,4).map(x=>({type:"Morador",title:x.user?.name??x.name??x.nome??"Morador",subtitle:labelApartment(x.apartment??{number:x.apartamento}),to:"/dashboard/moradores"})),
 ...(apartments??[]).filter(x=>textOf(x.block,x.bloco,x.number,x.numero).includes(needle)).slice(0,4).map(x=>({type:"Apartamento",title:labelApartment(x),subtitle:x.status??"",to:"/dashboard/apartamentos"})),
 ...(visitors??[]).filter(x=>textOf(x.name,x.nome,x.document,x.documento,x.apartment?.number,x.apartamento).includes(needle)).slice(0,4).map(x=>({type:"Visitante",title:x.name??x.nome??"Visitante",subtitle:labelApartment(x.apartment??{number:x.apartamento}),to:"/dashboard/visitantes"})),
 ...(packages??[]).filter(x=>textOf(x.internalCode,x.trackingCode,x.carrier,x.description,x.resident?.user?.name,x.apartment?.number).includes(needle)).slice(0,4).map(x=>({type:"Encomenda",title:x.internalCode??x.trackingCode??x.description??"Encomenda",subtitle:x.resident?.user?.name??labelApartment(x.apartment??{}),to:"/dashboard/encomendas"})),
 ...(occurrences??[]).filter(x=>textOf(x.title,x.description,x.category,x.apartment?.number).includes(needle)).slice(0,4).map(x=>({type:"Ocorrência",title:x.title??"Ocorrência",subtitle:x.category??"",to:"/dashboard/avisos"})),
 ]; setItems(all.slice(0,12)); setOpen(true);}catch{setItems([]);setOpen(true);}finally{setLoading(false);}},250); return()=>window.clearTimeout(timer.current);},[q]);
 function go(item){setOpen(false);setQ("");navigate(`${item.to}?q=${encodeURIComponent(item.title)}`);}
 return <div style={s.wrap}><div style={s.inputWrap}><span style={s.icon}>⌕</span><input aria-label="Busca global" style={s.input} value={q} onFocus={()=>q.trim().length>=2&&setOpen(true)} onChange={e=>setQ(e.target.value)} placeholder="Buscar morador, apartamento, visitante, encomenda ou ocorrência..."/>{loading&&<span style={s.loading}>Buscando...</span>}</div>{open&&<><div style={s.backdrop} onClick={()=>setOpen(false)}/><div style={s.panel}>{items.length===0?<div style={s.empty}>Nenhum resultado encontrado.</div>:items.map((item,i)=><button key={`${item.type}-${item.title}-${i}`} style={s.result} onClick={()=>go(item)}><span style={s.type}>{item.type}</span><span style={s.resultText}><strong>{item.title}</strong><small>{item.subtitle}</small></span><span style={s.arrow}>→</span></button>)}</div></>}</div>;
}
const s={wrap:{position:"relative",zIndex:80,marginBottom:16},inputWrap:{position:"relative",display:"flex",alignItems:"center",background:"#fff",border:"1px solid #e9e1f1",borderRadius:14,boxShadow:"0 8px 26px rgba(57,31,78,.06)"},icon:{position:"absolute",left:14,color:"var(--ic-primary)",fontSize:22,fontWeight:900},input:{width:"100%",boxSizing:"border-box",border:0,outline:"none",background:"transparent",padding:"13px 100px 13px 42px",fontSize:13,color:"#34253f"},loading:{position:"absolute",right:12,fontSize:10,color:"#8b7d95",fontWeight:800},backdrop:{position:"fixed",inset:0,zIndex:-1},panel:{position:"absolute",left:0,right:0,top:"calc(100% + 7px)",background:"#fff",border:"1px solid #e9e1f1",borderRadius:15,padding:7,boxShadow:"0 22px 60px rgba(47,29,58,.2)",maxHeight:"min(460px,65vh)",overflowY:"auto"},result:{width:"100%",border:0,background:"transparent",display:"flex",gap:10,alignItems:"center",padding:"10px",borderRadius:10,textAlign:"left",cursor:"pointer"},type:{minWidth:72,fontSize:9,fontWeight:900,textTransform:"uppercase",letterSpacing:.5,color:"var(--ic-primary-strong)",background:"var(--ic-primary-soft)",padding:"5px 7px",borderRadius:999,textAlign:"center"},resultText:{display:"grid",gap:2,flex:1,minWidth:0,color:"#34253f"},resultTextSmall:{fontSize:10},arrow:{color:"var(--ic-primary)",fontWeight:900},empty:{padding:20,textAlign:"center",color:"#8b7d95",fontSize:12}};
