import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import platformApi from "../../Services/platformApi.js";
import { PlatformCard, PlatformError, PlatformLoading, PlatformPageHeader } from "../../components/PlatformUi.jsx";

function brl(cents=0){return (Number(cents||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
function n(v){return Number(v??0)||0;}
export default function PlatformDashboard(){
 const [data,setData]=useState(null),[support,setSupport]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;Promise.all([platformApi.dashboard.get(),platformApi.support.ticketStatistics().catch(()=>null)]).then(([d,s])=>{if(active){setData(d?.dashboard??d??{});setSupport(s);}}).catch(e=>active&&setError(e?.message??"Não foi possível carregar a Central Star.")).finally(()=>active&&setLoading(false));return()=>{active=false};},[]);
 const d=data??{},c=d.condominiums??{},b=d.billing??{},a=b.amountsInCents??{},op=d.operation??{},sys=d.system?.events??{};
 const planData=[{name:"Ativos",value:n(c.active)+n(c.trial)},{name:"Pendentes",value:n(c.pending)},{name:"Suspensos",value:n(c.suspended)},{name:"Cancelados",value:n(c.canceled)}].filter(x=>x.value>0);
 const billingData=[{name:"Recebido",value:n(a.paid)},{name:"Pendente",value:n(a.pending)},{name:"Atrasado",value:n(a.overdue)}];
 const operationData=[{name:"Moradores",value:n(op.residents)},{name:"Porteiros",value:n(op.doormen)},{name:"Encomendas",value:n(op.packages)},{name:"Reservas",value:n(op.reservations)},{name:"Ocorrências",value:n(op.occurrences)}];
 if(loading)return <PlatformLoading text="Carregando dashboard executivo..."/>;
 return <div><style>{css}</style><PlatformPageHeader eyebrow="CENTRAL STAR INFINITY CODE" title="Dashboard executivo" description="Visão consolidada de carteira, receita, suporte, operação e integridade da plataforma."/><PlatformError message={error}/>
 <section className="hero"><div><span className="hero-kicker">VISÃO EXECUTIVA</span><h2>Star Infinity Code</h2><p>Indicadores centrais do InfinityCondo em tempo real.</p></div><div className="hero-money"><small>Receita registrada</small><strong>{brl(a.paid)}</strong><span>{n(c.active)+n(c.trial)} clientes ativos</span></div></section>
 <div className="metrics"><Metric label="Clientes ativos" value={n(c.active)+n(c.trial)} note={`${n(c.pending)} aguardando análise`}/><Metric label="Receita recebida" value={brl(a.paid)} note={`${brl(a.pending)} pendente`}/><Metric label="Inadimplência" value={brl(a.overdue)} note={`${n(b.charges?.overdue)} cobranças vencidas`} danger={n(a.overdue)>0}/><Metric label="SAs abertas" value={n(support?.open)} note={`${n(support?.critical)} críticas · ${n(support?.high)} altas`} danger={n(support?.critical)>0}/><Metric label="Eventos críticos" value={n(sys.critical)} note={`${n(sys.unresolved)} não resolvidos`} danger={n(sys.critical)>0}/><Metric label="Usuários" value={n(d.users?.total)} note={`${n(op.residents)} moradores`}/></div>
 <div className="charts"><PlatformCard><div className="chart-head"><div><span className="eyebrow">CARTEIRA</span><h3>Status dos condomínios</h3></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={planData} dataKey="value" nameKey="name" innerRadius={58} outerRadius={90} paddingAngle={3}>{planData.map((_,i)=><Cell key={i} fill={["var(--ic-primary-strong)","#f59e0b","#dc2626","#64748b"][i%4]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></PlatformCard>
 <PlatformCard><span className="eyebrow">FINANCEIRO</span><h3>Receita e exposição</h3><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={billingData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis tickFormatter={v=>`R$${Math.round(v/100)}`}/><Tooltip formatter={v=>brl(v)}/><Bar dataKey="value" radius={[8,8,0,0]} fill="var(--ic-primary)"/></BarChart></ResponsiveContainer></div></PlatformCard></div>
 <div className="charts"><PlatformCard><span className="eyebrow">OPERAÇÃO</span><h3>Volume por módulo</h3><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={operationData} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis dataKey="name" type="category" width={86}/><Tooltip/><Bar dataKey="value" fill="var(--ic-primary-dark)" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></div></PlatformCard><PlatformCard><span className="eyebrow">SAÚDE DA PLATAFORMA</span><h3>Controle operacional</h3><div className="health"><Health label="Backups verificados" value={n(d.backups?.verified)} ok={n(d.backups?.failed)===0}/><Health label="Comunicações entregues" value={n(d.communications?.delivered)} ok={n(d.communications?.failed)===0}/><Health label="Jobs concluídos" value={n(d.jobs?.success)} ok={n(d.jobs?.failed)===0}/><Health label="Eventos não resolvidos" value={n(sys.unresolved)} ok={n(sys.unresolved)===0}/></div></PlatformCard></div>
 </div>;
}
function Metric({label,value,note,danger}){return <PlatformCard><span className="eyebrow">{label}</span><strong className={danger?"metric danger":"metric"}>{value}</strong><small>{note}</small></PlatformCard>}
function Health({label,value,ok}){return <div className="health-row"><span className={ok?"dot ok":"dot"}/><div><strong>{label}</strong><small>{value}</small></div></div>}
const css=`.hero{display:flex;justify-content:space-between;gap:20px;align-items:center;flex-wrap:wrap;padding:24px;border-radius:20px;background:linear-gradient(135deg,var(--ic-primary-deepest),var(--ic-primary-dark) 58%,var(--ic-primary));color:#fff;margin-bottom:18px;box-shadow:0 22px 55px rgb(var(--ic-primary-deep-rgb) / .22)}.hero-kicker,.eyebrow{font-size:10px;font-weight:900;letter-spacing:1px;text-transform:uppercase;color:#8b7b96}.hero .hero-kicker{color:var(--ic-primary-border-soft)}.hero h2{font-size:clamp(26px,4vw,40px);margin:6px 0 4px}.hero p{margin:0;color:#e9ddff}.hero-money{display:grid;gap:4px;text-align:right}.hero-money strong{font-size:clamp(26px,4vw,40px)}.hero-money small,.hero-money span{color:var(--ic-primary-border-soft)}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(175px,1fr));gap:14px}.metric{display:block;margin:8px 0 5px;font-size:27px;color:var(--ic-primary-deep)}.metric.danger{color:#b91c1c}.metrics small{color:#85778e}.charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,360px),1fr));gap:14px;margin-top:14px}.charts h3{margin:5px 0 10px;color:#31213c}.chart{height:270px}.health{display:grid;gap:10px;margin-top:14px}.health-row{display:flex;align-items:center;gap:10px;padding:11px;border-radius:12px;background:#faf8fc;border:1px solid #eee8f5}.health-row div{display:flex;justify-content:space-between;gap:14px;flex:1}.health-row small{color:#7a6d84}.dot{width:10px;height:10px;border-radius:999px;background:#ef4444;box-shadow:0 0 0 4px #fee2e2}.dot.ok{background:#22c55e;box-shadow:0 0 0 4px #dcfce7}@media(max-width:650px){.hero-money{text-align:left}.chart{height:240px}}`;
