import { useEffect, useMemo, useState } from "react";
import platformApi from "../../Services/platformApi.js";
import { PlatformButton, PlatformCard, PlatformEmpty, PlatformError, PlatformLoading, PlatformPageHeader } from "../../components/PlatformUi.jsx";

const STATUS={OPEN:"Aberta",IN_PROGRESS:"Em atendimento",WAITING_CUSTOMER:"Aguardando cliente",RESOLVED:"Resolvida",CLOSED:"Encerrada"};
const PRIORITY={LOW:"Baixa",MEDIUM:"Média",HIGH:"Alta",CRITICAL:"Crítica"};
const priorityOrder={CRITICAL:0,HIGH:1,MEDIUM:2,LOW:3};
function formatDate(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"});}
function listOf(d){return Array.isArray(d)?d:d?.items??d?.data??[];}
export default function PlatformSupport(){
 const [tickets,setTickets]=useState([]),[stats,setStats]=useState(null),[current,setCurrent]=useState(null),[history,setHistory]=useState([]),[condos,setCondos]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false),[filter,setFilter]=useState("OPEN"),[modal,setModal]=useState(false),[form,setForm]=useState({condominiumId:"",reason:""});
 async function load(){setLoading(true);setError("");try{const[t,s,c,h,co]=await Promise.all([platformApi.support.tickets(),platformApi.support.ticketStatistics(),platformApi.support.current(),platformApi.support.history(),platformApi.condominiums.list("?limit=100&sortBy=name&sortOrder=asc")]);setTickets(listOf(t));setStats(s);setCurrent(c);setHistory(listOf(h));setCondos(listOf(co));}catch(e){setError(e?.message??"Falha ao carregar suporte.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>tickets.filter(t=>filter==="ALL"?true:filter==="OPEN"?["OPEN","IN_PROGRESS","WAITING_CUSTOMER"].includes(t.status):t.status===filter).sort((a,b)=>(priorityOrder[a.priority]??9)-(priorityOrder[b.priority]??9)||new Date(a.openedAt)-new Date(b.openedAt)),[tickets,filter]);
 async function update(id,payload){setSaving(true);setError("");try{await platformApi.support.updateTicket(id,payload);await load();}catch(e){setError(e?.message??"Não foi possível atualizar a solicitação.");}finally{setSaving(false);}}
 async function start(e){e.preventDefault();setSaving(true);setError("");try{await platformApi.support.start({condominiumId:form.condominiumId,reason:form.reason.trim()});setModal(false);setForm({condominiumId:"",reason:""});await load();}catch(err){setError(err?.message??"Não foi possível iniciar o atendimento.");}finally{setSaving(false);}}
 async function close(){if(!current?.id)return;setSaving(true);try{await platformApi.support.close(current.id);await load();}catch(e){setError(e?.message??"Não foi possível encerrar a sessão.");}finally{setSaving(false);}}
 if(loading)return <PlatformLoading text="Carregando Central de Suporte..."/>;
 return <div><style>{css}</style><PlatformPageHeader eyebrow="SUPORTE E OPERAÇÃO" title="Solicitações de Atendimento" description="Fila centralizada de SAs com classificação automática, prioridade, responsável e histórico." action={<PlatformButton variant="secondary" onClick={load}>Atualizar</PlatformButton>}/><PlatformError message={error}/>
 <div className="support-stats">{[["Abertas",stats?.open??0],["Críticas",stats?.critical??0],["Altas",stats?.high??0],["Aguardando cliente",stats?.waiting??0],["Resolvidas",stats?.resolved??0]].map(([l,v])=><PlatformCard key={l}><span className="eyebrow">{l}</span><strong className="big">{v}</strong></PlatformCard>)}</div>
 <PlatformCard style={{marginTop:18}}><div className="bar"><div><span className="eyebrow">FILA DE ATENDIMENTO</span><h3>Solicitações dos clientes</h3></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="select"><option value="OPEN">Em aberto</option><option value="ALL">Todas</option><option value="CRITICAL">Críticas</option><option value="RESOLVED">Resolvidas</option><option value="CLOSED">Encerradas</option></select></div>
 {filtered.length===0?<PlatformEmpty text="Nenhuma solicitação neste filtro."/>:<div className="tickets">{filtered.map(t=><div key={t.id} className="ticket"><div className="ticket-main"><div className="ticket-title">SA-{String(t.ticketNumber).padStart(5,"0")} · {t.title}</div><div className="meta">{t.condominium?.name??"Condomínio"} · {t.category} · aberta em {formatDate(t.openedAt)}</div><p>{t.description}</p><div className="chips"><span className={`priority p-${t.priority}`}>{PRIORITY[t.priority]??t.priority}</span><span className="status">{STATUS[t.status]??t.status}</span>{t.assignedTo?.name&&<span className="assignee">Responsável: {t.assignedTo.name}</span>}</div></div><div className="actions"><button disabled={saving} onClick={()=>update(t.id,{assignToMe:true,status:"IN_PROGRESS"})}>Assumir</button><button disabled={saving} onClick={()=>update(t.id,{status:"WAITING_CUSTOMER"})}>Aguardar cliente</button><button disabled={saving} onClick={()=>update(t.id,{status:"RESOLVED"})}>Resolver</button><select value={t.priority} onChange={e=>update(t.id,{priority:e.target.value})}><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></div></div>)}</div>}</PlatformCard>
 <div className="support-grid"><PlatformCard><div className="bar"><div><span className="eyebrow">ACESSO ASSISTIDO</span><h3>Sessão administrativa</h3></div>{current?.id?<PlatformButton variant="danger" onClick={close} disabled={saving}>Encerrar sessão</PlatformButton>:<PlatformButton onClick={()=>setModal(true)}>Iniciar sessão</PlatformButton>}</div>{current?.id?<div><strong>{current.condominium?.name??current.condominiumId}</strong><p>{current.reason}</p><small>Início: {formatDate(current.startedAt)}</small></div>:<PlatformEmpty text="Nenhuma sessão administrativa ativa."/>}</PlatformCard><PlatformCard><span className="eyebrow">HISTÓRICO DE ACESSOS</span><h3>{history.length} sessões registradas</h3><p className="muted">As sessões administrativas continuam disponíveis e auditadas separadamente das SAs.</p></PlatformCard></div>
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form className="modal" onSubmit={start}><h2>Iniciar sessão administrativa</h2><label>Condomínio<select required value={form.condominiumId} onChange={e=>setForm({...form,condominiumId:e.target.value})}>{<option value="">Selecione...</option>}{condos.filter(c=>!["CANCELED","REJECTED"].includes(c.status)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Motivo<textarea required minLength={5} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><div className="modal-actions"><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button disabled={saving}>Iniciar</button></div></form></div>}</div>;
}
const css=`.support-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px}.eyebrow{display:block;font-size:10px;font-weight:900;letter-spacing:.8px;color:#7c6d87}.big{display:block;margin-top:8px;font-size:28px;color:#5b21b6}.bar{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.bar h3{margin:4px 0 0;color:#2f1d3a}.select,.actions select,.modal select,.modal textarea{border:1px solid #ddd4e8;border-radius:10px;padding:9px 10px;background:#fff}.tickets{display:grid;gap:10px;margin-top:14px}.ticket{display:flex;justify-content:space-between;gap:16px;padding:15px;border:1px solid #eee8f5;border-radius:14px;background:#fcfaff;flex-wrap:wrap}.ticket-main{min-width:0;flex:1}.ticket-title{font-weight:900;color:#352044}.meta,.muted{font-size:11px;color:#8a7c94;margin-top:4px}.ticket p{color:#605269;font-size:12px;line-height:1.55}.chips{display:flex;gap:6px;flex-wrap:wrap}.priority,.status,.assignee{padding:5px 8px;border-radius:999px;font-size:10px;font-weight:900}.p-CRITICAL{background:#fee2e2;color:#991b1b}.p-HIGH{background:#ffedd5;color:#9a3412}.p-MEDIUM{background:#fef3c7;color:#92400e}.p-LOW{background:#ede9fe;color:#5b21b6}.status{background:#ede9fe;color:#5b21b6}.assignee{background:#ecfdf5;color:#166534}.actions{display:flex;gap:6px;align-items:flex-start;flex-wrap:wrap;max-width:360px}.actions button,.modal-actions button{border:1px solid #ddd4e8;border-radius:9px;padding:8px 10px;background:#fff;color:#5b21b6;font-weight:800;cursor:pointer}.support-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,320px),1fr));gap:14px;margin-top:18px}.overlay{position:fixed;inset:0;background:rgba(35,18,48,.55);display:grid;place-items:center;padding:18px;z-index:10000}.modal{width:min(520px,100%);background:#fff;border-radius:18px;padding:20px;display:grid;gap:14px}.modal label{display:grid;gap:6px;font-size:12px;font-weight:800;color:#55475f}.modal textarea{min-height:110px}.modal-actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:700px){.ticket{display:block}.actions{margin-top:12px;max-width:none}.actions button,.actions select{flex:1 1 130px}}`;
