import { useEffect, useMemo, useState } from "react";
import authApi from "../../Services/authApi.js";
import noticeApi from "../../Services/noticeApi.js";
import { downloadDataUrl, fileToDataUrl } from "../../utils/fileData.js";
import "../../styles/infinityModules.css";

const initial={title:"",message:"",agenda:"",eventDate:"",eventTime:"",eventLocation:"",eventModality:"PRESENCIAL",priority:"NORMAL",audience:"RESIDENTS",status:"PUBLISHED",files:[]};
const audienceLabels={ALL:"Todos",RESIDENTS:"Moradores",DOORMEN:"Porteiros",MANAGERS:"Gestão"};
const priorityLabels={LOW:"Baixa",NORMAL:"Normal",HIGH:"Alta",URGENT:"Urgente"};
export default function Assembleias(){
 const [user,setUser]=useState(null),[items,setItems]=useState([]),[form,setForm]=useState(initial),[editingId,setEditingId]=useState(null),[feedback,setFeedback]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState("");
 const manager=["CONDOMINIUM_ADMIN","MANAGER"].includes(user?.role);
 async function load(){setLoading(true);try{const [u,a]=await Promise.all([authApi.me(),noticeApi.list("?type=ASSEMBLY&publishedOnly=true")]);setUser(u);setItems(a??[]);}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível carregar as assembleias."});}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>items.filter(x=>{const q=search.trim().toLowerCase();return !q||[x.title,x.message,x.agenda,x.eventLocation].some(v=>String(v??"").toLowerCase().includes(q));}),[items,search]);
 function edit(x){setEditingId(x.id);setForm({title:x.title??"",message:x.message??"",agenda:x.agenda??"",eventDate:x.eventDate?String(x.eventDate).slice(0,10):"",eventTime:x.eventTime??"",eventLocation:x.eventLocation??"",eventModality:x.eventModality??"PRESENCIAL",priority:x.priority??"NORMAL",audience:x.audience??"RESIDENTS",status:x.status??"PUBLISHED",files:[]});setFeedback(null);window.scrollTo({top:0,behavior:"smooth"});}
 function reset(){setEditingId(null);setForm(initial);}
 async function save(e){e.preventDefault();setFeedback(null);setSaving(true);try{const attachmentFiles=[];for(const file of form.files){attachmentFiles.push({fileName:file.name,dataUrl:await fileToDataUrl(file, 1536 * 1024)});}const payload={type:"ASSEMBLY",title:form.title,message:form.message,category:"Assembleia",agenda:form.agenda,eventDate:form.eventDate,eventTime:form.eventTime,eventLocation:form.eventLocation,eventModality:form.eventModality||null,priority:form.priority,audience:form.audience,apartmentId:null};if(!editingId)payload.status=form.status;if(form.files.length)payload.attachmentFiles=attachmentFiles;if(editingId)await noticeApi.update(editingId,payload);else await noticeApi.create(payload);setFeedback({type:"ok",text:editingId?"Assembleia atualizada.":"Assembleia cadastrada e comunicada conforme a publicação."});reset();await load();}catch(err){setFeedback({type:"error",text:err?.details?.[0]?.message??err?.message??"Não foi possível salvar a assembleia."});}finally{setSaving(false);}}
 async function download(x,index){try{const f=await noticeApi.downloadAttachment(x.id,index);downloadDataUrl(f.dataUrl,f.fileName);}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível baixar o anexo."});}}
 async function remove(id){try{await noticeApi.remove(id);setFeedback({type:"ok",text:"Assembleia removida."});if(editingId===id)reset();await load();}catch(e){setFeedback({type:"error",text:e?.message??"Não foi possível remover a assembleia."});}}
 return <div className="icm-page"><section className="icm-hero"><div><span className="icm-kicker">🏛️ Comunicação formal</span><h1>Assembleias</h1><p>Convocações organizadas com pauta, data, horário, local e anexos, integradas à estrutura de avisos e notificações do InfinityCondo.</p></div><div className="icm-hero-count"><strong>{items.length}</strong><span>assembleias</span></div></section>{feedback&&<div className={`icm-message icm-message-${feedback.type}`}>{feedback.text}</div>}
 {manager&&<form className="icm-card icm-form" onSubmit={save}><h2>{editingId?"Editar assembleia":"Nova assembleia"}</h2><div className="icm-form-grid"><F label="Título *"><input className="icm-input" required minLength={3} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></F><F label="Público *"><select className="icm-select" value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="RESIDENTS">Moradores</option><option value="ALL">Todos</option><option value="DOORMEN">Porteiros</option><option value="MANAGERS">Gestão</option></select></F><F label="Data *"><input className="icm-input" type="date" required value={form.eventDate} onChange={e=>setForm({...form,eventDate:e.target.value})}/></F><F label="Horário *"><input className="icm-input" type="time" required value={form.eventTime} onChange={e=>setForm({...form,eventTime:e.target.value})}/></F><F label="Local *"><input className="icm-input" required value={form.eventLocation} onChange={e=>setForm({...form,eventLocation:e.target.value})}/></F><F label="Modalidade"><select className="icm-select" value={form.eventModality} onChange={e=>setForm({...form,eventModality:e.target.value})}><option value="PRESENCIAL">Presencial</option><option value="ONLINE">Online</option><option value="HIBRIDA">Híbrida</option></select></F><F label="Prioridade"><select className="icm-select" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{Object.entries(priorityLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></F>{!editingId&&<F label="Publicação"><select className="icm-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="PUBLISHED">Publicar</option><option value="DRAFT">Salvar como rascunho</option></select></F>}<F label="Resumo / convocação *" full><textarea className="icm-textarea" required minLength={3} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></F><F label="Pauta *" full><textarea className="icm-textarea" required value={form.agenda} onChange={e=>setForm({...form,agenda:e.target.value})} placeholder="Descreva os itens que serão tratados."/></F><F label={editingId?"Substituir anexos (até 5, 1,5 MB cada)":"Anexos (até 5, 1,5 MB cada)"} full><input className="icm-input" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.txt,.jpg,.jpeg,.png,.webp" onChange={e=>setForm({...form,files:Array.from(e.target.files??[]).slice(0,5)})}/></F></div><div className="icm-actions"><button className="icm-btn icm-btn-primary" disabled={saving}>{saving?"Salvando...":editingId?"Salvar alterações":"Cadastrar assembleia"}</button>{editingId&&<button type="button" className="icm-btn icm-btn-neutral" onClick={reset}>Cancelar edição</button>}</div></form>}
 <div className="icm-toolbar"><input className="icm-input" placeholder="Buscar assembleia..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading?<div className="icm-card icm-empty">Carregando assembleias...</div>:filtered.length===0?<div className="icm-card icm-empty">Nenhuma assembleia publicada para este perfil.</div>:<div className="icm-grid">{filtered.map(x=><article className="icm-card" key={x.id}><h3>{x.title}</h3><div className="icm-meta"><span className="icm-pill">{x.eventDate?new Date(x.eventDate).toLocaleDateString("pt-BR",{timeZone:"UTC"}):"Data não informada"} · {x.eventTime||""}</span><span className="icm-pill">{audienceLabels[x.audience]||x.audience}</span></div><p>{x.message}</p><div className="icm-subtle"><strong>Pauta</strong><div style={{whiteSpace:"pre-wrap",marginTop:6}}>{x.agenda}</div></div><div className="icm-detail-grid"><div><span>Local</span><strong>{x.eventLocation}</strong></div><div><span>Modalidade</span><strong>{x.eventModality||"—"}</strong></div></div>{Array.isArray(x.attachments)&&x.attachments.length>0&&<div className="icm-actions">{x.attachments.map((a,i)=><button key={`${x.id}-${i}`} className="icm-btn icm-btn-soft" onClick={()=>download(x,i)}>📎 {a.fileName||`Anexo ${i+1}`}</button>)}</div>}{manager&&<div className="icm-actions"><button className="icm-btn icm-btn-neutral" onClick={()=>edit(x)}>Editar</button><button className="icm-btn icm-btn-danger" onClick={()=>remove(x.id)}>Remover</button></div>}</article>)}</div>}</div>;
}
function F({label,full=false,children}){return <div className={`icm-field${full?" icm-field-full":""}`}><label>{label}</label>{children}</div>}
