import { useEffect, useMemo, useState } from "react";
import authApi from "../../Services/authApi.js";
import documentApi from "../../Services/documentApi.js";
import { downloadDataUrl, fileToDataUrl } from "../../utils/fileData.js";
import "../../styles/infinityModules.css";

const categories = [["CONVENCAO","Convenção"],["REGIMENTO_INTERNO","Regimento interno"],["ATA","Ata"],["CIRCULAR","Circular"],["CONTRATO","Contrato"],["PRESTACAO_CONTAS","Prestação de contas"],["COMUNICADO","Comunicado"],["OUTROS","Outros"]];
const visibilities = [["MANAGERS_ONLY","Somente gestão"],["RESIDENTS","Moradores"],["DOORMEN","Porteiros"],["ALL","Moradores e porteiros"]];
const initialForm = { title:"", description:"", category:"COMUNICADO", visibility:"RESIDENTS", documentDate:"", file:null };
const labelOf = (items,value) => items.find(([key])=>key===value)?.[1] ?? value;
const bytes = value => { const n=Number(value)||0; if(n<1024)return `${n} B`; if(n<1024*1024)return `${Math.max(1,Math.round(n/1024))} KB`; return `${(n/1024/1024).toFixed(1)} MB`; };
const iconFor = name => { const ext=String(name??"").split(".").pop()?.toLowerCase(); if(ext==="pdf")return "📕"; if(["xls","xlsx"].includes(ext))return "📊"; if(["doc","docx"].includes(ext))return "📝"; if(["jpg","jpeg","png","webp"].includes(ext))return "🖼️"; return "📄"; };

export default function DocumentosCondominio(){
 const [user,setUser]=useState(null),[items,setItems]=useState([]),[form,setForm]=useState(initialForm),[editingId,setEditingId]=useState(null),[search,setSearch]=useState(""),[category,setCategory]=useState(""),[feedback,setFeedback]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const manager=["CONDOMINIUM_ADMIN","MANAGER"].includes(user?.role);
 async function load(){setLoading(true);try{const [currentUser,documents]=await Promise.all([authApi.me(),documentApi.list()]);setUser(currentUser);setItems(documents??[]);}catch(error){setFeedback({type:"error",text:error?.message??"Não foi possível carregar os documentos."});}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>items.filter(item=>{const text=search.trim().toLowerCase();const matches=!text||[item.title,item.description,item.category,item.fileName].some(v=>String(v??"").toLowerCase().includes(text));return matches&&(!category||item.category===category);}),[items,search,category]);
 const metrics=useMemo(()=>({residents:items.filter(x=>["RESIDENTS","ALL"].includes(x.visibility)).length,doormen:items.filter(x=>["DOORMEN","ALL"].includes(x.visibility)).length,management:items.filter(x=>x.visibility==="MANAGERS_ONLY").length,size:items.reduce((sum,x)=>sum+(Number(x.fileSize)||0),0)}),[items]);
 function edit(item){setEditingId(item.id);setForm({title:item.title??"",description:item.description??"",category:item.category??"COMUNICADO",visibility:item.visibility??"MANAGERS_ONLY",documentDate:item.documentDate?String(item.documentDate).slice(0,10):"",file:null});setFeedback(null);window.scrollTo?.({top:0,behavior:"smooth"});}
 function resetForm(){setEditingId(null);setForm(initialForm);}
 async function save(event){event.preventDefault();setFeedback(null);if(!editingId&&!form.file){setFeedback({type:"error",text:"Selecione o arquivo do documento."});return;}setSaving(true);try{const payload={title:form.title,description:form.description||null,category:form.category,visibility:form.visibility,documentDate:form.documentDate||null};if(form.file){payload.fileName=form.file.name;payload.fileDataUrl=await fileToDataUrl(form.file);}if(editingId)await documentApi.update(editingId,payload);else await documentApi.create(payload);setFeedback({type:"ok",text:editingId?"Documento atualizado.":"Documento cadastrado na Central de Documentos."});resetForm();await load();}catch(error){setFeedback({type:"error",text:error?.details?.[0]?.message??error?.message??"Não foi possível salvar o documento."});}finally{setSaving(false);}}
 async function download(item){setFeedback(null);try{const file=await documentApi.download(item.id);downloadDataUrl(file.dataUrl,file.fileName||item.fileName);}catch(error){setFeedback({type:"error",text:error?.message??"Não foi possível baixar o documento."});}}
 async function preview(item){setFeedback(null);try{const file=await documentApi.download(item.id);if(!file?.dataUrl)throw new Error("Arquivo indisponível.");const w=window.open("","_blank","noopener,noreferrer");if(w)w.location.href=file.dataUrl;else downloadDataUrl(file.dataUrl,file.fileName||item.fileName);}catch(error){setFeedback({type:"error",text:error?.message??"Não foi possível visualizar o documento."});}}
 async function remove(id){setFeedback(null);try{await documentApi.remove(id);if(editingId===id)resetForm();setFeedback({type:"ok",text:"Documento removido."});await load();}catch(error){setFeedback({type:"error",text:error?.message??"Não foi possível remover o documento."});}}
 return <div className="icm-page">
  <section className="icm-hero"><div><span className="icm-kicker">📚 Gestão documental</span><h1>Central de Documentos</h1><p>Organize convenção, regimento, atas, circulares, prestação de contas e demais arquivos do condomínio com acesso controlado por perfil.</p></div><div className="icm-hero-count"><strong>{items.length}</strong><span>no acervo</span></div></section>
  <section className="icm-metrics"><div className="icm-metric"><span>Visíveis a moradores</span><strong>{metrics.residents}</strong></div><div className="icm-metric"><span>Visíveis à portaria</span><strong>{metrics.doormen}</strong></div><div className="icm-metric"><span>Somente gestão</span><strong>{metrics.management}</strong></div><div className="icm-metric"><span>Armazenamento do acervo</span><strong style={{fontSize:20}}>{bytes(metrics.size)}</strong></div></section>
  {feedback&&<div className={`icm-message icm-message-${feedback.type}`}>{feedback.text}</div>}
  {manager&&<form className="icm-card icm-form" onSubmit={save}><h2>{editingId?"Editar documento":"Adicionar ao acervo"}</h2><div className="icm-form-grid"><F label="Título *"><input className="icm-input" required minLength={2} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></F><F label="Categoria *"><select className="icm-select" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></F><F label="Quem pode visualizar *"><select className="icm-select" value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}>{visibilities.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></F><F label="Data do documento"><input className="icm-input" type="date" value={form.documentDate} onChange={e=>setForm({...form,documentDate:e.target.value})}/></F><F label="Descrição" full><textarea className="icm-textarea" placeholder="Descreva o conteúdo ou a finalidade deste documento." value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></F><F label={editingId?"Substituir arquivo (opcional)":"Arquivo *"} full><div className="icm-dropzone"><strong>{form.file?`${iconFor(form.file.name)} ${form.file.name}`:"Arraste/seleciona o arquivo pelo campo abaixo"}</strong><div className="icm-muted">PDF, Word, Excel, texto ou imagem, até 8 MB. O banco armazena somente metadados e o caminho do arquivo.</div><input style={{marginTop:10}} className="icm-input" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.txt,.jpg,.jpeg,.png,.webp" onChange={e=>setForm({...form,file:e.target.files?.[0]??null})}/></div></F></div><div className="icm-actions"><button className="icm-btn icm-btn-primary" disabled={saving}>{saving?"Salvando...":editingId?"Salvar alterações":"Adicionar documento"}</button>{editingId&&<button type="button" className="icm-btn icm-btn-neutral" onClick={resetForm}>Cancelar edição</button>}</div></form>}
  <div className="icm-toolbar"><input className="icm-input" placeholder="Buscar por título, descrição ou arquivo..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="icm-select" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
  {loading?<div className="icm-card icm-empty">Carregando documentos...</div>:filtered.length===0?<div className="icm-card icm-empty">Nenhum documento disponível para este perfil.</div>:<div className="icm-grid">{filtered.map(item=><article className="icm-card" key={item.id}><div className="icm-title-row"><span className="icm-file-icon">{iconFor(item.fileName)}</span><div><h3>{item.title}</h3><div className="icm-muted">{item.fileName} · {bytes(item.fileSize)}</div></div></div><div className="icm-meta"><span className="icm-pill">{labelOf(categories,item.category)}</span><span className="icm-pill">{labelOf(visibilities,item.visibility)}</span></div><p className="icm-muted">{item.description||"Sem descrição."}</p><div className="icm-detail-grid"><div><span>Data do documento</span><strong>{item.documentDate?new Date(item.documentDate).toLocaleDateString("pt-BR",{timeZone:"UTC"}):"Não informada"}</strong></div><div><span>Incluído em</span><strong>{item.createdAt?new Date(item.createdAt).toLocaleDateString("pt-BR"):"—"}</strong></div></div><div className="icm-actions"><button className="icm-btn icm-btn-soft" onClick={()=>preview(item)}>Visualizar</button><button className="icm-btn icm-btn-primary" onClick={()=>download(item)}>Baixar</button>{manager&&<><button className="icm-btn icm-btn-neutral" onClick={()=>edit(item)}>Editar</button><button className="icm-btn icm-btn-danger" onClick={()=>remove(item.id)}>Remover</button></>}</div></article>)}</div>}
 </div>;
}
function F({label,full=false,children}){return <div className={`icm-field${full?" icm-field-full":""}`}><label>{label}</label>{children}</div>}
